//===-- CAPI.cpp ------------------------------------------------*- C++ -*-===//
//
// Part of the LLZK Project, under the Apache License v2.0.
// See LICENSE.txt for license information.
// Copyright 2026 Project LLZK
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
///
/// \file
/// This file includes the autogenerated CAPI functions to load the passes.
///
//===----------------------------------------------------------------------===//

#include "r1cs/Transforms/TransformationPasses.h" // IWYU pragma: keep

#include "llzk-c/Target/R1CS.h"

#include <mlir/CAPI/Pass.h>

using namespace r1cs;

/// Adapt the C API group name to the C++ transformation pass registration function.
static inline void registerR1CSTransformationPasses() { registerTransformationPasses(); }

#include "r1cs/Transforms/TransformationPasses.capi.cpp.inc"
