//===-- CAPI.cpp ------------------------------------------------*- C++ -*-===//
//
// Part of the LLZK Project, under the Apache License v2.0.
// See LICENSE.txt for license information.
// Copyright 2025 Veridise Inc.
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
///
/// \file
/// This file includes the autogenerated CAPI functions to load the passes.
///
//===----------------------------------------------------------------------===//

#include "pcl/Conversion/ConversionPasses.h" // IWYU pragma: keep

#include <mlir/CAPI/Pass.h>

#include "pcl/Conversion/ConversionPasses.capi.h.inc"

using namespace pcl;

// Impl
#include "pcl/Conversion/ConversionPasses.capi.cpp.inc"
