//===-- SMTInfo.td - SMT script metadata dialect -----------*- tablegen -*-===//
//
// Part of the LLZK Project, under the Apache License v2.0.
// See LICENSE.txt for license information.
// Copyright 2026 Project LLZK
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

#ifndef LLZK_DIALECT_SMTINFO_IR_SMTINFO_TD
#define LLZK_DIALECT_SMTINFO_IR_SMTINFO_TD

include "SMTInfoAttributes.td"
include "SMTInfoDialect.td"
include "SMTInfoOps.td"

#endif // LLZK_DIALECT_SMTINFO_IR_SMTINFO_TD
