var searchData=
[
  ['parameters_3a_0',['Parameters:',['../dialects.html#parameters',1,'Parameters:'],['../dialects.html#parameters-1',1,'Parameters:'],['../dialects.html#parameters-2',1,'Parameters:'],['../dialects.html#parameters-3',1,'Parameters:'],['../dialects.html#parameters-4',1,'Parameters:'],['../dialects.html#parameters-5',1,'Parameters:'],['../dialects.html#parameters-6',1,'Parameters:'],['../dialects.html#parameters-7',1,'Parameters:'],['../dialects.html#parameters-8',1,'Parameters:'],['../dialects.html#parameters-9',1,'Parameters:'],['../backend-dialects.html#parameters-10',1,'Parameters:']]],
  ['params_1',['&lt;span class=&quot;tt&quot;&gt;-llzk-drop-empty-params&lt;/span&gt;',['../tools.html#autotoc_md-llzk-drop-empty-params',1,'']]],
  ['pass_2',['&lt;span class=&quot;tt&quot;&gt;-llzk-poly-lowering-pass&lt;/span&gt;',['../tools.html#autotoc_md-llzk-poly-lowering-pass',1,'']]],
  ['pass_20documentation_3',['LLZK Pass Documentation',['../tools.html#passes',1,'']]],
  ['passes_4',['Passes',['../tools.html#array-dialect-transformation-passes',1,''array' Dialect Transformation Passes'],['../tools.html#polymorphic-dialect-transformation-passes',1,''polymorphic' Dialect Transformation Passes'],['../tools.html#analysis-passes',1,'Analysis Passes'],['../tools.html#general-transformation-passes',1,'General Transformation Passes'],['../overview.html#pass-overview',1,'Passes'],['../tools.html#validation-passes',1,'Validation Passes']]],
  ['patches_5',['Patches',['../maintanence.html#patches',1,'']]],
  ['permanent_20ban_6',['4. Permanent Ban',['../code-of-conduct.html#autotoc_md4-permanent-ban',1,'']]],
  ['philosophy_7',['Contribution Philosophy',['../contribution-guide.html#contribution-philosophy',1,'']]],
  ['pledge_8',['Our Pledge',['../code-of-conduct.html#our-pledge',1,'']]],
  ['pod_20dialect_9',['&apos;pod&apos; Dialect',['../dialects.html#pod-dialect',1,'']]],
  ['pod_20new_20_3a_3allzk_3a_3apod_3a_3anewpodop_10',['&lt;span class=&quot;tt&quot;&gt;pod.new&lt;/span&gt; (llzk::pod::NewPodOp)',['../dialects.html#podnew-llzkpodnewpodop',1,'']]],
  ['pod_20read_20_3a_3allzk_3a_3apod_3a_3areadpodop_11',['&lt;span class=&quot;tt&quot;&gt;pod.read&lt;/span&gt; (llzk::pod::ReadPodOp)',['../dialects.html#podread-llzkpodreadpodop',1,'']]],
  ['pod_20write_20_3a_3allzk_3a_3apod_3a_3awritepodop_12',['&lt;span class=&quot;tt&quot;&gt;pod.write&lt;/span&gt; (llzk::pod::WritePodOp)',['../dialects.html#podwrite-llzkpodwritepodop',1,'']]],
  ['podtype_13',['PodType',['../dialects.html#podtype',1,'']]],
  ['poly_20applymap_20_3a_3allzk_3a_3apolymorphic_3a_3aapplymapop_14',['&lt;span class=&quot;tt&quot;&gt;poly.applymap&lt;/span&gt; (llzk::polymorphic::ApplyMapOp)',['../dialects.html#polyapplymap-llzkpolymorphicapplymapop',1,'']]],
  ['poly_20dialect_15',['&apos;poly&apos; Dialect',['../dialects.html#poly-dialect',1,'']]],
  ['poly_20lowering_20pass_16',['&lt;span class=&quot;tt&quot;&gt;-llzk-poly-lowering-pass&lt;/span&gt;',['../tools.html#autotoc_md-llzk-poly-lowering-pass',1,'']]],
  ['poly_20read_5fconst_20_3a_3allzk_3a_3apolymorphic_3a_3aconstreadop_17',['&lt;span class=&quot;tt&quot;&gt;poly.read_const&lt;/span&gt; (llzk::polymorphic::ConstReadOp)',['../dialects.html#polyread_const-llzkpolymorphicconstreadop',1,'']]],
  ['poly_20unifiable_5fcast_20_3a_3allzk_3a_3apolymorphic_3a_3aunifiablecastop_18',['&lt;span class=&quot;tt&quot;&gt;poly.unifiable_cast&lt;/span&gt; (llzk::polymorphic::UnifiableCastOp)',['../dialects.html#polyunifiable_cast-llzkpolymorphicunifiablecastop',1,'']]],
  ['polymorphic_20dialect_20transformation_20passes_19',['&apos;polymorphic&apos; Dialect Transformation Passes',['../tools.html#polymorphic-dialect-transformation-passes',1,'']]],
  ['pow_20_3a_3allzk_3a_3afelt_3a_3apowfeltop_20',['&lt;span class=&quot;tt&quot;&gt;felt.pow&lt;/span&gt; (llzk::felt::PowFeltOp)',['../dialects.html#feltpow-llzkfeltpowfeltop',1,'']]],
  ['pr_20is_20merged_21',['Your PR is merged!',['../contribution-guide.html#your-pr-is-merged',1,'']]],
  ['practices_20checklist_22',['Best Practices Checklist',['../contribution-guide.html#best-practices-checklist',1,'']]],
  ['predecessors_23',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-predecessors&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-predecessors',1,'']]],
  ['preparing_20a_20new_20release_24',['Preparing a new release',['../maintanence.html#preparing-a-new-release',1,'']]],
  ['print_20call_20graph_25',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-call-graph&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-call-graph',1,'']]],
  ['print_20call_20graph_20sccs_26',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-call-graph-sccs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-call-graph-sccs',1,'']]],
  ['print_20constraint_20dependency_20graphs_27',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-constraint-dependency-graphs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-constraint-dependency-graphs',1,'']]],
  ['print_20interval_20analysis_28',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-interval-analysis&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-interval-analysis',1,'']]],
  ['print_20predecessors_29',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-predecessors&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-predecessors',1,'']]],
  ['print_20symbol_20def_20tree_30',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-symbol-def-tree&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-symbol-def-tree',1,'']]],
  ['print_20symbol_20use_20graph_31',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-symbol-use-graph&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-symbol-use-graph',1,'']]],
  ['product_32',['&lt;span class=&quot;tt&quot;&gt;-llzk-compute-constrain-to-product&lt;/span&gt;',['../tools.html#autotoc_md-llzk-compute-constrain-to-product',1,'']]],
  ['product_20loops_33',['&lt;span class=&quot;tt&quot;&gt;-llzk-fuse-product-loops&lt;/span&gt;',['../tools.html#autotoc_md-llzk-fuse-product-loops',1,'']]],
  ['project_20overview_34',['Project Overview',['../overview.html#project-overview',1,'']]],
  ['pseudo_20homogeneous_20arrays_35',['Pseudo-homogeneous arrays',['../syntax.html#pseudo-homogeneous',1,'']]],
  ['publicattr_36',['PublicAttr',['../dialects.html#publicattr',1,'PublicAttr'],['../backend-dialects.html#publicattr-1',1,'PublicAttr']]],
  ['pull_20request_37',['Pull Request',['../contribution-guide.html#pull-request',1,'']]],
  ['pull_20request_20review_38',['Pull Request Review',['../contribution-guide.html#pull-request-review',1,'']]]
];
