var searchData=
[
  ['backend_0',['Backend',['../pcl-backend.html',1,'PCL Backend'],['../r1cs-backend.html',1,'R1CS Backend'],['../smt-backend.html',1,'SMT Backend'],['../zklean-backend.html',1,'ZKLean Backend']]],
  ['backends_1',['Backends',['../backends-page.html',1,'Backends'],['../overview.html#backends',1,'Backends'],['../tools.html#backends-1',1,'Backends']]],
  ['ban_2',['Ban',['../code-of-conduct.html#autotoc_md3-temporary-ban',1,'3. Temporary Ban'],['../code-of-conduct.html#autotoc_md4-permanent-ban',1,'4. Permanent Ban']]],
  ['basic_20usage_3',['Basic Usage',['../tools.html#basic-usage',1,'Basic Usage'],['../tools.html#basic-usage-1',1,'Basic Usage']]],
  ['behavior_4',['Behavior',['../tools.html#behavior',1,'']]],
  ['best_20practices_20checklist_5',['Best Practices Checklist',['../contribution-guide.html#best-practices-checklist',1,'']]],
  ['bit_5fand_20_3a_3allzk_3a_3afelt_3a_3aandfeltop_6',['&lt;span class=&quot;tt&quot;&gt;felt.bit_and&lt;/span&gt; (llzk::felt::AndFeltOp)',['../dialects.html#feltbit_and-llzkfeltandfeltop',1,'']]],
  ['bit_5fnot_20_3a_3allzk_3a_3afelt_3a_3anotfeltop_7',['&lt;span class=&quot;tt&quot;&gt;felt.bit_not&lt;/span&gt; (llzk::felt::NotFeltOp)',['../dialects.html#feltbit_not-llzkfeltnotfeltop',1,'']]],
  ['bit_5for_20_3a_3allzk_3a_3afelt_3a_3aorfeltop_8',['&lt;span class=&quot;tt&quot;&gt;felt.bit_or&lt;/span&gt; (llzk::felt::OrFeltOp)',['../dialects.html#feltbit_or-llzkfeltorfeltop',1,'']]],
  ['bit_5fxor_20_3a_3allzk_3a_3afelt_3a_3axorfeltop_9',['&lt;span class=&quot;tt&quot;&gt;felt.bit_xor&lt;/span&gt; (llzk::felt::XorFeltOp)',['../dialects.html#feltbit_xor-llzkfeltxorfeltop',1,'']]],
  ['bitvectorattr_10',['BitVectorAttr',['../smt-backend.html#bitvectorattr',1,'']]],
  ['bitvectortype_11',['BitVectorType',['../smt-backend.html#bitvectortype',1,'']]],
  ['bool_20and_20_3a_3allzk_3a_3aboolean_3a_3aandboolop_12',['&lt;span class=&quot;tt&quot;&gt;bool.and&lt;/span&gt; (llzk::boolean::AndBoolOp)',['../dialects.html#booland-llzkbooleanandboolop',1,'']]],
  ['bool_20assert_20_3a_3allzk_3a_3aboolean_3a_3aassertop_13',['&lt;span class=&quot;tt&quot;&gt;bool.assert&lt;/span&gt; (llzk::boolean::AssertOp)',['../dialects.html#boolassert-llzkbooleanassertop',1,'']]],
  ['bool_20cmp_20_3a_3allzk_3a_3aboolean_3a_3acmpop_14',['&lt;span class=&quot;tt&quot;&gt;bool.cmp&lt;/span&gt; (llzk::boolean::CmpOp)',['../dialects.html#boolcmp-llzkbooleancmpop',1,'']]],
  ['bool_20dialect_15',['&apos;bool&apos; Dialect',['../dialects.html#bool-dialect',1,'']]],
  ['bool_20exists_20_3a_3allzk_3a_3aboolean_3a_3aexistsop_16',['&lt;span class=&quot;tt&quot;&gt;bool.exists&lt;/span&gt; (llzk::boolean::ExistsOp)',['../dialects.html#boolexists-llzkbooleanexistsop',1,'']]],
  ['bool_20forall_20_3a_3allzk_3a_3aboolean_3a_3aforallop_17',['&lt;span class=&quot;tt&quot;&gt;bool.forall&lt;/span&gt; (llzk::boolean::ForAllOp)',['../dialects.html#boolforall-llzkbooleanforallop',1,'']]],
  ['bool_20not_20_3a_3allzk_3a_3aboolean_3a_3anotboolop_18',['&lt;span class=&quot;tt&quot;&gt;bool.not&lt;/span&gt; (llzk::boolean::NotBoolOp)',['../dialects.html#boolnot-llzkbooleannotboolop',1,'']]],
  ['bool_20or_20_3a_3allzk_3a_3aboolean_3a_3aorboolop_19',['&lt;span class=&quot;tt&quot;&gt;bool.or&lt;/span&gt; (llzk::boolean::OrBoolOp)',['../dialects.html#boolor-llzkbooleanorboolop',1,'']]],
  ['bool_20quantifiers_20',['&lt;span class=&quot;tt&quot;&gt;-llzk-lower-bool-quantifiers&lt;/span&gt;',['../tools.html#autotoc_md-llzk-lower-bool-quantifiers',1,'']]],
  ['bool_20xor_20_3a_3allzk_3a_3aboolean_3a_3axorboolop_21',['&lt;span class=&quot;tt&quot;&gt;bool.xor&lt;/span&gt; (llzk::boolean::XorBoolOp)',['../dialects.html#boolxor-llzkbooleanxorboolop',1,'']]],
  ['bool_20yield_20_3a_3allzk_3a_3aboolean_3a_3ayieldop_22',['&lt;span class=&quot;tt&quot;&gt;bool.yield&lt;/span&gt; (llzk::boolean::YieldOp)',['../dialects.html#boolyield-llzkbooleanyieldop',1,'']]],
  ['boolattr_23',['BoolAttr',['../pcl-backend.html#boolattr',1,'']]],
  ['booltype_24',['BoolType',['../smt-backend.html#booltype',1,'BoolType'],['../pcl-backend.html#booltype-1',1,'BoolType']]],
  ['broadcast_20_3a_3allzk_3a_3asmt_3a_3aarraybroadcastop_25',['&lt;span class=&quot;tt&quot;&gt;smt.array.broadcast&lt;/span&gt; (llzk::smt::ArrayBroadcastOp)',['../smt-backend.html#smtarraybroadcast-llzksmtarraybroadcastop',1,'']]],
  ['build_20setup_26',['Manual Build Setup',['../setup.html#manual-build-setup',1,'']]],
  ['bv_20add_20_3a_3allzk_3a_3asmt_3a_3abvaddop_27',['&lt;span class=&quot;tt&quot;&gt;smt.bv.add&lt;/span&gt; (llzk::smt::BVAddOp)',['../smt-backend.html#smtbvadd-llzksmtbvaddop',1,'']]],
  ['bv_20and_20_3a_3allzk_3a_3asmt_3a_3abvandop_28',['&lt;span class=&quot;tt&quot;&gt;smt.bv.and&lt;/span&gt; (llzk::smt::BVAndOp)',['../smt-backend.html#smtbvand-llzksmtbvandop',1,'']]],
  ['bv_20ashr_20_3a_3allzk_3a_3asmt_3a_3abvashrop_29',['&lt;span class=&quot;tt&quot;&gt;smt.bv.ashr&lt;/span&gt; (llzk::smt::BVAShrOp)',['../smt-backend.html#smtbvashr-llzksmtbvashrop',1,'']]],
  ['bv_20cmp_20_3a_3allzk_3a_3asmt_3a_3abvcmpop_30',['&lt;span class=&quot;tt&quot;&gt;smt.bv.cmp&lt;/span&gt; (llzk::smt::BVCmpOp)',['../smt-backend.html#smtbvcmp-llzksmtbvcmpop',1,'']]],
  ['bv_20concat_20_3a_3allzk_3a_3asmt_3a_3aconcatop_31',['&lt;span class=&quot;tt&quot;&gt;smt.bv.concat&lt;/span&gt; (llzk::smt::ConcatOp)',['../smt-backend.html#smtbvconcat-llzksmtconcatop',1,'']]],
  ['bv_20constant_20_3a_3allzk_3a_3asmt_3a_3abvconstantop_32',['&lt;span class=&quot;tt&quot;&gt;smt.bv.constant&lt;/span&gt; (llzk::smt::BVConstantOp)',['../smt-backend.html#smtbvconstant-llzksmtbvconstantop',1,'']]],
  ['bv_20extract_20_3a_3allzk_3a_3asmt_3a_3aextractop_33',['&lt;span class=&quot;tt&quot;&gt;smt.bv.extract&lt;/span&gt; (llzk::smt::ExtractOp)',['../smt-backend.html#smtbvextract-llzksmtextractop',1,'']]],
  ['bv_20lshr_20_3a_3allzk_3a_3asmt_3a_3abvlshrop_34',['&lt;span class=&quot;tt&quot;&gt;smt.bv.lshr&lt;/span&gt; (llzk::smt::BVLShrOp)',['../smt-backend.html#smtbvlshr-llzksmtbvlshrop',1,'']]],
  ['bv_20mul_20_3a_3allzk_3a_3asmt_3a_3abvmulop_35',['&lt;span class=&quot;tt&quot;&gt;smt.bv.mul&lt;/span&gt; (llzk::smt::BVMulOp)',['../smt-backend.html#smtbvmul-llzksmtbvmulop',1,'']]],
  ['bv_20neg_20_3a_3allzk_3a_3asmt_3a_3abvnegop_36',['&lt;span class=&quot;tt&quot;&gt;smt.bv.neg&lt;/span&gt; (llzk::smt::BVNegOp)',['../smt-backend.html#smtbvneg-llzksmtbvnegop',1,'']]],
  ['bv_20not_20_3a_3allzk_3a_3asmt_3a_3abvnotop_37',['&lt;span class=&quot;tt&quot;&gt;smt.bv.not&lt;/span&gt; (llzk::smt::BVNotOp)',['../smt-backend.html#smtbvnot-llzksmtbvnotop',1,'']]],
  ['bv_20or_20_3a_3allzk_3a_3asmt_3a_3abvorop_38',['&lt;span class=&quot;tt&quot;&gt;smt.bv.or&lt;/span&gt; (llzk::smt::BVOrOp)',['../smt-backend.html#smtbvor-llzksmtbvorop',1,'']]],
  ['bv_20repeat_20_3a_3allzk_3a_3asmt_3a_3arepeatop_39',['&lt;span class=&quot;tt&quot;&gt;smt.bv.repeat&lt;/span&gt; (llzk::smt::RepeatOp)',['../smt-backend.html#smtbvrepeat-llzksmtrepeatop',1,'']]],
  ['bv_20sdiv_20_3a_3allzk_3a_3asmt_3a_3abvsdivop_40',['&lt;span class=&quot;tt&quot;&gt;smt.bv.sdiv&lt;/span&gt; (llzk::smt::BVSDivOp)',['../smt-backend.html#smtbvsdiv-llzksmtbvsdivop',1,'']]],
  ['bv_20shl_20_3a_3allzk_3a_3asmt_3a_3abvshlop_41',['&lt;span class=&quot;tt&quot;&gt;smt.bv.shl&lt;/span&gt; (llzk::smt::BVShlOp)',['../smt-backend.html#smtbvshl-llzksmtbvshlop',1,'']]],
  ['bv_20smod_20_3a_3allzk_3a_3asmt_3a_3abvsmodop_42',['&lt;span class=&quot;tt&quot;&gt;smt.bv.smod&lt;/span&gt; (llzk::smt::BVSModOp)',['../smt-backend.html#smtbvsmod-llzksmtbvsmodop',1,'']]],
  ['bv_20srem_20_3a_3allzk_3a_3asmt_3a_3abvsremop_43',['&lt;span class=&quot;tt&quot;&gt;smt.bv.srem&lt;/span&gt; (llzk::smt::BVSRemOp)',['../smt-backend.html#smtbvsrem-llzksmtbvsremop',1,'']]],
  ['bv_20udiv_20_3a_3allzk_3a_3asmt_3a_3abvudivop_44',['&lt;span class=&quot;tt&quot;&gt;smt.bv.udiv&lt;/span&gt; (llzk::smt::BVUDivOp)',['../smt-backend.html#smtbvudiv-llzksmtbvudivop',1,'']]],
  ['bv_20urem_20_3a_3allzk_3a_3asmt_3a_3abvuremop_45',['&lt;span class=&quot;tt&quot;&gt;smt.bv.urem&lt;/span&gt; (llzk::smt::BVURemOp)',['../smt-backend.html#smtbvurem-llzksmtbvuremop',1,'']]],
  ['bv_20xor_20_3a_3allzk_3a_3asmt_3a_3abvxorop_46',['&lt;span class=&quot;tt&quot;&gt;smt.bv.xor&lt;/span&gt; (llzk::smt::BVXOrOp)',['../smt-backend.html#smtbvxor-llzksmtbvxorop',1,'']]],
  ['bv2int_20_3a_3allzk_3a_3asmt_3a_3abv2intop_47',['&lt;span class=&quot;tt&quot;&gt;smt.bv2int&lt;/span&gt; (llzk::smt::BV2IntOp)',['../smt-backend.html#smtbv2int-llzksmtbv2intop',1,'']]],
  ['bvcmppredicate_48',['BVCmpPredicate',['../smt-backend.html#bvcmppredicate',1,'']]]
];
