var searchData=
[
  ['scalar_0',['&lt;span class=&quot;tt&quot;&gt;-llzk-array-to-scalar&lt;/span&gt;',['../tools.html#autotoc_md-llzk-array-to-scalar',1,'']]],
  ['sccs_1',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-call-graph-sccs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-call-graph-sccs',1,'']]],
  ['scope_2',['Scope',['../code-of-conduct.html#scope',1,'']]],
  ['semantic_20rules_3',['Semantic Rules',['../syntax.html#semantic-rules',1,'']]],
  ['server_4',['llzk-lsp-server',['../tools.html#llzk-lsp-server',1,'']]],
  ['setup_5',['Setup',['../setup.html#manual-build-setup',1,'Manual Build Setup'],['../setup.html#nix-setup',1,'Nix Setup'],['../setup.html',1,'Setup']]],
  ['shl_20_3a_3allzk_3a_3afelt_3a_3ashlfeltop_6',['&lt;span class=&quot;tt&quot;&gt;felt.shl&lt;/span&gt; (llzk::felt::ShlFeltOp)',['../dialects.html#feltshl-llzkfeltshlfeltop',1,'']]],
  ['shr_20_3a_3allzk_3a_3afelt_3a_3ashrfeltop_7',['&lt;span class=&quot;tt&quot;&gt;felt.shr&lt;/span&gt; (llzk::felt::ShrFeltOp)',['../dialects.html#feltshr-llzkfeltshrfeltop',1,'']]],
  ['signaltype_8',['SignalType',['../backend-dialects.html#signaltype',1,'']]],
  ['sintdiv_20_3a_3allzk_3a_3afelt_3a_3asignedintdivfeltop_9',['&lt;span class=&quot;tt&quot;&gt;felt.sintdiv&lt;/span&gt; (llzk::felt::SignedIntDivFeltOp)',['../dialects.html#feltsintdiv-llzkfeltsignedintdivfeltop',1,'']]],
  ['site_20organization_10',['Site Organization',['../index.html#site-organization',1,'']]],
  ['smod_20_3a_3allzk_3a_3afelt_3a_3asignedmodfeltop_11',['&lt;span class=&quot;tt&quot;&gt;felt.smod&lt;/span&gt; (llzk::felt::SignedModFeltOp)',['../dialects.html#feltsmod-llzkfeltsignedmodfeltop',1,'']]],
  ['solve_20an_20issue_12',['Solve an issue',['../contribution-guide.html#solve-an-issue',1,'']]],
  ['specific_20options_13',['LLZK-Specific Options',['../tools.html#llzk-specific-options',1,'']]],
  ['specification_14',['LLZK Language Specification',['../syntax.html',1,'']]],
  ['standards_15',['Our Standards',['../code-of-conduct.html#our-standards',1,'']]],
  ['started_16',['Getting started',['../contribution-guide.html#getting-started',1,'']]],
  ['string_20dialect_17',['&apos;string&apos; Dialect',['../dialects.html#string-dialect',1,'']]],
  ['string_20new_20_3a_3allzk_3a_3astring_3a_3alitstringop_18',['&lt;span class=&quot;tt&quot;&gt;string.new&lt;/span&gt; (llzk::string::LitStringOp)',['../dialects.html#stringnew-llzkstringlitstringop',1,'']]],
  ['stringtype_19',['StringType',['../dialects.html#stringtype',1,'']]],
  ['struct_20def_20_3a_3allzk_3a_3acomponent_3a_3astructdefop_20',['&lt;span class=&quot;tt&quot;&gt;struct.def&lt;/span&gt; (llzk::component::StructDefOp)',['../dialects.html#structdef-llzkcomponentstructdefop',1,'']]],
  ['struct_20dialect_21',['&apos;struct&apos; Dialect',['../dialects.html#struct-dialect',1,'']]],
  ['struct_20member_20_3a_3allzk_3a_3acomponent_3a_3amemberdefop_22',['&lt;span class=&quot;tt&quot;&gt;struct.member&lt;/span&gt; (llzk::component::MemberDefOp)',['../dialects.html#structmember-llzkcomponentmemberdefop',1,'']]],
  ['struct_20new_20_3a_3allzk_3a_3acomponent_3a_3acreatestructop_23',['&lt;span class=&quot;tt&quot;&gt;struct.new&lt;/span&gt; (llzk::component::CreateStructOp)',['../dialects.html#structnew-llzkcomponentcreatestructop',1,'']]],
  ['struct_20readm_20_3a_3allzk_3a_3acomponent_3a_3amemberreadop_24',['&lt;span class=&quot;tt&quot;&gt;struct.readm&lt;/span&gt; (llzk::component::MemberReadOp)',['../dialects.html#structreadm-llzkcomponentmemberreadop',1,'']]],
  ['struct_20writem_20_3a_3allzk_3a_3acomponent_3a_3amemberwriteop_25',['&lt;span class=&quot;tt&quot;&gt;struct.writem&lt;/span&gt; (llzk::component::MemberWriteOp)',['../dialects.html#structwritem-llzkcomponentmemberwriteop',1,'']]],
  ['structs_26',['&lt;span class=&quot;tt&quot;&gt;-llzk-inline-structs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-inline-structs',1,'']]],
  ['structtype_27',['StructType',['../dialects.html#structtype',1,'']]],
  ['sub_20_3a_3allzk_3a_3afelt_3a_3asubfeltop_28',['&lt;span class=&quot;tt&quot;&gt;felt.sub&lt;/span&gt; (llzk::felt::SubFeltOp)',['../dialects.html#feltsub-llzkfeltsubfeltop',1,'']]],
  ['symbol_20def_20tree_29',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-symbol-def-tree&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-symbol-def-tree',1,'']]],
  ['symbol_20use_20graph_30',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-symbol-use-graph&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-symbol-use-graph',1,'']]],
  ['syntax_31',['Syntax',['../syntax.html#syntax-1',1,'']]]
];
