var searchData=
[
  ['language_20specification_0',['LLZK Language Specification',['../syntax.html',1,'']]],
  ['len_20_3a_3allzk_3a_3aarray_3a_3aarraylengthop_1',['&lt;span class=&quot;tt&quot;&gt;array.len&lt;/span&gt; (llzk::array::ArrayLengthOp)',['../dialects.html#arraylen-llzkarrayarraylengthop',1,'']]],
  ['license_2',['LLZK License',['../license.html',1,'index']]],
  ['lineartype_3',['LinearType',['../backend-dialects.html#lineartype',1,'']]],
  ['list_4',['Todo List',['../todo.html',1,'']]],
  ['llzk_20array_20to_20scalar_5',['&lt;span class=&quot;tt&quot;&gt;-llzk-array-to-scalar&lt;/span&gt;',['../tools.html#autotoc_md-llzk-array-to-scalar',1,'']]],
  ['llzk_20compute_20constrain_20to_20product_6',['&lt;span class=&quot;tt&quot;&gt;-llzk-compute-constrain-to-product&lt;/span&gt;',['../tools.html#autotoc_md-llzk-compute-constrain-to-product',1,'']]],
  ['llzk_20dialect_7',['&apos;llzk&apos; Dialect',['../dialects.html#llzk-dialect',1,'']]],
  ['llzk_20drop_20empty_20params_8',['&lt;span class=&quot;tt&quot;&gt;-llzk-drop-empty-params&lt;/span&gt;',['../tools.html#autotoc_md-llzk-drop-empty-params',1,'']]],
  ['llzk_20duplicate_20op_20elim_9',['&lt;span class=&quot;tt&quot;&gt;-llzk-duplicate-op-elim&lt;/span&gt;',['../tools.html#autotoc_md-llzk-duplicate-op-elim',1,'']]],
  ['llzk_20duplicate_20read_20write_20elim_10',['&lt;span class=&quot;tt&quot;&gt;-llzk-duplicate-read-write-elim&lt;/span&gt;',['../tools.html#autotoc_md-llzk-duplicate-read-write-elim',1,'']]],
  ['llzk_20flatten_11',['&lt;span class=&quot;tt&quot;&gt;-llzk-flatten&lt;/span&gt;',['../tools.html#autotoc_md-llzk-flatten',1,'']]],
  ['llzk_20fuse_20product_20loops_12',['&lt;span class=&quot;tt&quot;&gt;-llzk-fuse-product-loops&lt;/span&gt;',['../tools.html#autotoc_md-llzk-fuse-product-loops',1,'']]],
  ['llzk_20inline_20structs_13',['&lt;span class=&quot;tt&quot;&gt;-llzk-inline-structs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-inline-structs',1,'']]],
  ['llzk_20ir_20dialects_14',['LLZK IR Dialects',['../dialects.html',1,'LLZK IR Dialects'],['../overview.html#llzk-ir-dialects',1,'LLZK IR Dialects']]],
  ['llzk_20language_20specification_15',['LLZK Language Specification',['../syntax.html',1,'']]],
  ['llzk_20license_16',['LLZK License',['../license.html',1,'index']]],
  ['llzk_20lsp_20server_17',['llzk-lsp-server',['../tools.html#llzk-lsp-server',1,'']]],
  ['llzk_20nondet_20_3a_3allzk_3a_3anondetop_18',['&lt;span class=&quot;tt&quot;&gt;llzk.nondet&lt;/span&gt; (llzk::NonDetOp)',['../dialects.html#llzknondet-llzknondetop',1,'']]],
  ['llzk_20opt_19',['llzk-opt',['../tools.html#llzk-opt',1,'']]],
  ['llzk_20pass_20documentation_20',['LLZK Pass Documentation',['../tools.html#passes',1,'']]],
  ['llzk_20poly_20lowering_20pass_21',['&lt;span class=&quot;tt&quot;&gt;-llzk-poly-lowering-pass&lt;/span&gt;',['../tools.html#autotoc_md-llzk-poly-lowering-pass',1,'']]],
  ['llzk_20print_20call_20graph_22',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-call-graph&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-call-graph',1,'']]],
  ['llzk_20print_20call_20graph_20sccs_23',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-call-graph-sccs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-call-graph-sccs',1,'']]],
  ['llzk_20print_20constraint_20dependency_20graphs_24',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-constraint-dependency-graphs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-constraint-dependency-graphs',1,'']]],
  ['llzk_20print_20interval_20analysis_25',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-interval-analysis&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-interval-analysis',1,'']]],
  ['llzk_20print_20predecessors_26',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-predecessors&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-predecessors',1,'']]],
  ['llzk_20print_20symbol_20def_20tree_27',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-symbol-def-tree&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-symbol-def-tree',1,'']]],
  ['llzk_20print_20symbol_20use_20graph_28',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-symbol-use-graph&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-symbol-use-graph',1,'']]],
  ['llzk_20specific_20options_29',['LLZK-Specific Options',['../tools.html#llzk-specific-options',1,'']]],
  ['llzk_20unused_20declaration_20elim_30',['&lt;span class=&quot;tt&quot;&gt;-llzk-unused-declaration-elim&lt;/span&gt;',['../tools.html#autotoc_md-llzk-unused-declaration-elim',1,'']]],
  ['llzk_20validate_20member_20writes_31',['&lt;span class=&quot;tt&quot;&gt;-llzk-validate-member-writes&lt;/span&gt;',['../tools.html#autotoc_md-llzk-validate-member-writes',1,'']]],
  ['loopboundsattr_32',['LoopBoundsAttr',['../dialects.html#loopboundsattr',1,'']]],
  ['loops_33',['&lt;span class=&quot;tt&quot;&gt;-llzk-fuse-product-loops&lt;/span&gt;',['../tools.html#autotoc_md-llzk-fuse-product-loops',1,'']]],
  ['lowering_20pass_34',['&lt;span class=&quot;tt&quot;&gt;-llzk-poly-lowering-pass&lt;/span&gt;',['../tools.html#autotoc_md-llzk-poly-lowering-pass',1,'']]],
  ['lsp_20server_35',['llzk-lsp-server',['../tools.html#llzk-lsp-server',1,'']]]
];
