var searchData=
[
  ['call_20_3a_3allzk_3a_3afunction_3a_3acallop_0',['&lt;span class=&quot;tt&quot;&gt;function.call&lt;/span&gt; (llzk::function::CallOp)',['../dialects.html#functioncall-llzkfunctioncallop',1,'']]],
  ['call_20graph_1',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-call-graph&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-call-graph',1,'']]],
  ['call_20graph_20sccs_2',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-call-graph-sccs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-call-graph-sccs',1,'']]],
  ['candidate_3',['Creating the Release Candidate',['../maintanence.html#creating-the-release-candidate',1,'']]],
  ['cases_3a_4',['Cases:',['../dialects.html#cases',1,'']]],
  ['cast_20dialect_5',['&apos;cast&apos; Dialect',['../dialects.html#cast-dialect',1,'']]],
  ['cast_20tofelt_20_3a_3allzk_3a_3acast_3a_3ainttofeltop_6',['&lt;span class=&quot;tt&quot;&gt;cast.tofelt&lt;/span&gt; (llzk::cast::IntToFeltOp)',['../dialects.html#casttofelt-llzkcastinttofeltop',1,'']]],
  ['cast_20toindex_20_3a_3allzk_3a_3acast_3a_3afelttoindexop_7',['&lt;span class=&quot;tt&quot;&gt;cast.toindex&lt;/span&gt; (llzk::cast::FeltToIndexOp)',['../dialects.html#casttoindex-llzkcastfelttoindexop',1,'']]],
  ['changes_8',['Make Changes',['../contribution-guide.html#make-changes',1,'']]],
  ['checklist_9',['Best Practices Checklist',['../contribution-guide.html#best-practices-checklist',1,'']]],
  ['circuit_20_3a_3ar1cs_3a_3acircuitdefop_10',['&lt;span class=&quot;tt&quot;&gt;r1cs.circuit&lt;/span&gt; (r1cs::CircuitDefOp)',['../backend-dialects.html#r1cscircuit-r1cscircuitdefop',1,'']]],
  ['cmp_20_3a_3allzk_3a_3aboolean_3a_3acmpop_11',['&lt;span class=&quot;tt&quot;&gt;bool.cmp&lt;/span&gt; (llzk::boolean::CmpOp)',['../dialects.html#boolcmp-llzkbooleancmpop',1,'']]],
  ['code_20of_20conduct_12',['Contributor Covenant Code of Conduct',['../code-of-conduct.html',1,'contribution-guide']]],
  ['commit_20your_20update_13',['Commit your update',['../contribution-guide.html#commit-your-update',1,'']]],
  ['compute_20constrain_20to_20product_14',['&lt;span class=&quot;tt&quot;&gt;-llzk-compute-constrain-to-product&lt;/span&gt;',['../tools.html#autotoc_md-llzk-compute-constrain-to-product',1,'']]],
  ['conduct_15',['Contributor Covenant Code of Conduct',['../code-of-conduct.html',1,'contribution-guide']]],
  ['const_20_3a_3allzk_3a_3afelt_3a_3afeltconstantop_16',['&lt;span class=&quot;tt&quot;&gt;felt.const&lt;/span&gt; (llzk::felt::FeltConstantOp)',['../dialects.html#feltconst-llzkfeltfeltconstantop',1,'']]],
  ['const_20_3a_3ar1cs_3a_3aconstop_17',['&lt;span class=&quot;tt&quot;&gt;r1cs.const&lt;/span&gt; (r1cs::ConstOp)',['../backend-dialects.html#r1csconst-r1csconstop',1,'']]],
  ['constrain_20_3a_3ar1cs_3a_3aconstrainop_18',['&lt;span class=&quot;tt&quot;&gt;r1cs.constrain&lt;/span&gt; (r1cs::ConstrainOp)',['../backend-dialects.html#r1csconstrain-r1csconstrainop',1,'']]],
  ['constrain_20dialect_19',['&apos;constrain&apos; Dialect',['../dialects.html#constrain-dialect',1,'']]],
  ['constrain_20eq_20_3a_3allzk_3a_3aconstrain_3a_3aemitequalityop_20',['&lt;span class=&quot;tt&quot;&gt;constrain.eq&lt;/span&gt; (llzk::constrain::EmitEqualityOp)',['../dialects.html#constraineq-llzkconstrainemitequalityop',1,'']]],
  ['constrain_20in_20_3a_3allzk_3a_3aconstrain_3a_3aemitcontainmentop_21',['&lt;span class=&quot;tt&quot;&gt;constrain.in&lt;/span&gt; (llzk::constrain::EmitContainmentOp)',['../dialects.html#constrainin-llzkconstrainemitcontainmentop',1,'']]],
  ['constrain_20to_20product_22',['&lt;span class=&quot;tt&quot;&gt;-llzk-compute-constrain-to-product&lt;/span&gt;',['../tools.html#autotoc_md-llzk-compute-constrain-to-product',1,'']]],
  ['constraint_20dependency_20graphs_23',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-constraint-dependency-graphs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-constraint-dependency-graphs',1,'']]],
  ['contribution_20guide_24',['Contribution Guide',['../contribution-guide.html',1,'']]],
  ['contribution_20philosophy_25',['Contribution Philosophy',['../contribution-guide.html#contribution-philosophy',1,'']]],
  ['contributor_20covenant_20code_20of_20conduct_26',['Contributor Covenant Code of Conduct',['../code-of-conduct.html',1,'contribution-guide']]],
  ['correction_27',['1. Correction',['../code-of-conduct.html#autotoc_md1-correction',1,'']]],
  ['covenant_20code_20of_20conduct_28',['Contributor Covenant Code of Conduct',['../code-of-conduct.html',1,'contribution-guide']]],
  ['create_20a_20new_20issue_29',['Create a new issue',['../contribution-guide.html#create-a-new-issue',1,'']]],
  ['create_20the_20release_30',['Create the Release',['../maintanence.html#create-the-release',1,'']]],
  ['creating_20the_20release_20candidate_31',['Creating the Release Candidate',['../maintanence.html#creating-the-release-candidate',1,'']]]
];
