var searchData=
[
  ['call_20_3a_3allzk_3a_3afunction_3a_3acallop_0',['&lt;span class=&quot;tt&quot;&gt;function.call&lt;/span&gt; (llzk::function::CallOp)',['../dialects.html#functioncall-llzkfunctioncallop',1,'']]],
  ['call_20_3a_3allzk_3a_3azkleanlean_3a_3acallop_1',['&lt;span class=&quot;tt&quot;&gt;ZKLeanLean.call&lt;/span&gt; (llzk::zkleanlean::CallOp)',['../zklean-backend.html#zkleanleancall-llzkzkleanleancallop',1,'']]],
  ['call_20graph_2',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-call-graph&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-call-graph',1,'']]],
  ['call_20graph_20sccs_3',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-call-graph-sccs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-call-graph-sccs',1,'']]],
  ['candidate_4',['Creating the Release Candidate',['../maintanence.html#creating-the-release-candidate',1,'']]],
  ['cases_3a_5',['Cases:',['../dialects.html#cases',1,'Cases:'],['../dialects.html#cases-1',1,'Cases:'],['../smt-backend.html#cases-2',1,'Cases:'],['../smt-backend.html#cases-3',1,'Cases:']]],
  ['cast_20dialect_6',['&apos;cast&apos; Dialect',['../dialects.html#cast-dialect',1,'']]],
  ['cast_20tofelt_20_3a_3allzk_3a_3acast_3a_3ainttofeltop_7',['&lt;span class=&quot;tt&quot;&gt;cast.tofelt&lt;/span&gt; (llzk::cast::IntToFeltOp)',['../dialects.html#casttofelt-llzkcastinttofeltop',1,'']]],
  ['cast_20toindex_20_3a_3allzk_3a_3acast_3a_3afelttoindexop_8',['&lt;span class=&quot;tt&quot;&gt;cast.toindex&lt;/span&gt; (llzk::cast::FeltToIndexOp)',['../dialects.html#casttoindex-llzkcastfelttoindexop',1,'']]],
  ['changes_9',['Make Changes',['../contribution-guide.html#make-changes',1,'']]],
  ['check_10',['llzk-smt-check',['../tools.html#llzk-smt-check',1,'']]],
  ['check_20_3a_3allzk_3a_3asmt_3a_3acheckop_11',['&lt;span class=&quot;tt&quot;&gt;smt.check&lt;/span&gt; (llzk::smt::CheckOp)',['../smt-backend.html#smtcheck-llzksmtcheckop',1,'']]],
  ['checklist_12',['Best Practices Checklist',['../contribution-guide.html#best-practices-checklist',1,'']]],
  ['circuit_20_3a_3ar1cs_3a_3acircuitdefop_13',['&lt;span class=&quot;tt&quot;&gt;r1cs.circuit&lt;/span&gt; (r1cs::CircuitDefOp)',['../r1cs-backend.html#r1cscircuit-r1cscircuitdefop',1,'']]],
  ['cmp_20_3a_3allzk_3a_3aboolean_3a_3acmpop_14',['&lt;span class=&quot;tt&quot;&gt;bool.cmp&lt;/span&gt; (llzk::boolean::CmpOp)',['../dialects.html#boolcmp-llzkbooleancmpop',1,'']]],
  ['cmp_20_3a_3allzk_3a_3asmt_3a_3abvcmpop_15',['&lt;span class=&quot;tt&quot;&gt;smt.bv.cmp&lt;/span&gt; (llzk::smt::BVCmpOp)',['../smt-backend.html#smtbvcmp-llzksmtbvcmpop',1,'']]],
  ['cmp_20_3a_3allzk_3a_3asmt_3a_3aintcmpop_16',['&lt;span class=&quot;tt&quot;&gt;smt.int.cmp&lt;/span&gt; (llzk::smt::IntCmpOp)',['../smt-backend.html#smtintcmp-llzksmtintcmpop',1,'']]],
  ['code_20of_20conduct_17',['Contributor Covenant Code of Conduct',['../code-of-conduct.html',1,'contribution-guide']]],
  ['commit_20your_20update_18',['Commit your update',['../contribution-guide.html#commit-your-update',1,'']]],
  ['composedlookuptabletype_19',['ComposedLookupTableType',['../zklean-backend.html#composedlookuptabletype',1,'']]],
  ['compute_20constrain_20to_20product_20',['&lt;span class=&quot;tt&quot;&gt;-llzk-compute-constrain-to-product&lt;/span&gt;',['../tools.html#autotoc_md-llzk-compute-constrain-to-product',1,'']]],
  ['concat_20_3a_3allzk_3a_3asmt_3a_3aconcatop_21',['&lt;span class=&quot;tt&quot;&gt;smt.bv.concat&lt;/span&gt; (llzk::smt::ConcatOp)',['../smt-backend.html#smtbvconcat-llzksmtconcatop',1,'']]],
  ['conduct_22',['Contributor Covenant Code of Conduct',['../code-of-conduct.html',1,'contribution-guide']]],
  ['const_20_3a_3allzk_3a_3afelt_3a_3afeltconstantop_23',['&lt;span class=&quot;tt&quot;&gt;felt.const&lt;/span&gt; (llzk::felt::FeltConstantOp)',['../dialects.html#feltconst-llzkfeltfeltconstantop',1,'']]],
  ['const_20_3a_3apcl_3a_3aconstop_24',['&lt;span class=&quot;tt&quot;&gt;pcl.const&lt;/span&gt; (pcl::ConstOp)',['../pcl-backend.html#pclconst-pclconstop',1,'']]],
  ['const_20_3a_3ar1cs_3a_3aconstop_25',['&lt;span class=&quot;tt&quot;&gt;r1cs.const&lt;/span&gt; (r1cs::ConstOp)',['../r1cs-backend.html#r1csconst-r1csconstop',1,'']]],
  ['constant_20_3a_3allzk_3a_3asmt_3a_3aboolconstantop_26',['&lt;span class=&quot;tt&quot;&gt;smt.constant&lt;/span&gt; (llzk::smt::BoolConstantOp)',['../smt-backend.html#smtconstant-llzksmtboolconstantop',1,'']]],
  ['constant_20_3a_3allzk_3a_3asmt_3a_3abvconstantop_27',['&lt;span class=&quot;tt&quot;&gt;smt.bv.constant&lt;/span&gt; (llzk::smt::BVConstantOp)',['../smt-backend.html#smtbvconstant-llzksmtbvconstantop',1,'']]],
  ['constant_20_3a_3allzk_3a_3asmt_3a_3aintconstantop_28',['&lt;span class=&quot;tt&quot;&gt;smt.int.constant&lt;/span&gt; (llzk::smt::IntConstantOp)',['../smt-backend.html#smtintconstant-llzksmtintconstantop',1,'']]],
  ['constrain_20_3a_3ar1cs_3a_3aconstrainop_29',['&lt;span class=&quot;tt&quot;&gt;r1cs.constrain&lt;/span&gt; (r1cs::ConstrainOp)',['../r1cs-backend.html#r1csconstrain-r1csconstrainop',1,'']]],
  ['constrain_20dialect_30',['&apos;constrain&apos; Dialect',['../dialects.html#constrain-dialect',1,'']]],
  ['constrain_20eq_20_3a_3allzk_3a_3aconstrain_3a_3aemitequalityop_31',['&lt;span class=&quot;tt&quot;&gt;constrain.eq&lt;/span&gt; (llzk::constrain::EmitEqualityOp)',['../dialects.html#constraineq-llzkconstrainemitequalityop',1,'']]],
  ['constrain_20in_20_3a_3allzk_3a_3aconstrain_3a_3aemitcontainmentop_32',['&lt;span class=&quot;tt&quot;&gt;constrain.in&lt;/span&gt; (llzk::constrain::EmitContainmentOp)',['../dialects.html#constrainin-llzkconstrainemitcontainmentop',1,'']]],
  ['constrain_20to_20product_33',['&lt;span class=&quot;tt&quot;&gt;-llzk-compute-constrain-to-product&lt;/span&gt;',['../tools.html#autotoc_md-llzk-compute-constrain-to-product',1,'']]],
  ['constraineq_20_3a_3allzk_3a_3azkbuilder_3a_3aconstraineqop_34',['&lt;span class=&quot;tt&quot;&gt;ZKBuilder.ConstrainEq&lt;/span&gt; (llzk::zkbuilder::ConstrainEqOp)',['../zklean-backend.html#zkbuilderconstraineq-llzkzkbuilderconstraineqop',1,'']]],
  ['constrainr1cs_20_3a_3allzk_3a_3azkbuilder_3a_3aconstrainr1csop_35',['&lt;span class=&quot;tt&quot;&gt;ZKBuilder.ConstrainR1CS&lt;/span&gt; (llzk::zkbuilder::ConstrainR1CSOp)',['../zklean-backend.html#zkbuilderconstrainr1cs-llzkzkbuilderconstrainr1csop',1,'']]],
  ['constraint_20dependency_20graphs_36',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-constraint-dependency-graphs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-constraint-dependency-graphs',1,'']]],
  ['contribution_20guide_37',['Contribution Guide',['../contribution-guide.html',1,'']]],
  ['contribution_20philosophy_38',['Contribution Philosophy',['../contribution-guide.html#contribution-philosophy',1,'']]],
  ['contributor_20covenant_20code_20of_20conduct_39',['Contributor Covenant Code of Conduct',['../code-of-conduct.html',1,'contribution-guide']]],
  ['control_20flow_40',['&lt;span class=&quot;tt&quot;&gt;-llzk-fuse-product-control-flow&lt;/span&gt;',['../tools.html#autotoc_md-llzk-fuse-product-control-flow',1,'']]],
  ['correction_41',['1. Correction',['../code-of-conduct.html#autotoc_md1-correction',1,'']]],
  ['covenant_20code_20of_20conduct_42',['Contributor Covenant Code of Conduct',['../code-of-conduct.html',1,'contribution-guide']]],
  ['create_20a_20new_20issue_43',['Create a new issue',['../contribution-guide.html#create-a-new-issue',1,'']]],
  ['create_20the_20release_44',['Create the Release',['../maintanence.html#create-the-release',1,'']]],
  ['creating_20the_20release_20candidate_45',['Creating the Release Candidate',['../maintanence.html#creating-the-release-candidate',1,'']]]
];
