var searchData=
[
  ['scalar_0',['scalar',['../tools.html#autotoc_md-llzk-array-to-scalar',1,'&lt;span class=&quot;tt&quot;&gt;-llzk-array-to-scalar&lt;/span&gt;'],['../tools.html#autotoc_md-llzk-pod-to-scalar',1,'&lt;span class=&quot;tt&quot;&gt;-llzk-pod-to-scalar&lt;/span&gt;']]],
  ['sccs_1',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-call-graph-sccs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-call-graph-sccs',1,'']]],
  ['schema_2',['File schema',['../md_doc_2doxygen_214__wtns__format.html#file-schema',1,'']]],
  ['scope_3',['Scope',['../code-of-conduct.html#scope',1,'']]],
  ['semantic_20rules_4',['Semantic Rules',['../syntax.html#semantic-rules',1,'']]],
  ['server_5',['llzk-lsp-server',['../tools.html#llzk-lsp-server',1,'']]],
  ['set_20_3a_3allzk_3a_3asmt_5finfo_3a_3asmtinfosetop_6',['&lt;span class=&quot;tt&quot;&gt;smt_info.set&lt;/span&gt; (llzk::smt_info::SMTInfoSetOp)',['../smt-backend.html#smt_infoset-llzksmt_infosmtinfosetop',1,'']]],
  ['setup_7',['Setup',['../setup.html#manual-build-setup',1,'Manual Build Setup'],['../setup.html#nix-setup',1,'Nix Setup'],['../setup.html',1,'Setup']]],
  ['shl_20_3a_3allzk_3a_3afelt_3a_3ashlfeltop_8',['&lt;span class=&quot;tt&quot;&gt;felt.shl&lt;/span&gt; (llzk::felt::ShlFeltOp)',['../dialects.html#feltshl-llzkfeltshlfeltop',1,'']]],
  ['shr_20_3a_3allzk_3a_3afelt_3a_3ashrfeltop_9',['&lt;span class=&quot;tt&quot;&gt;felt.shr&lt;/span&gt; (llzk::felt::ShrFeltOp)',['../dialects.html#feltshr-llzkfeltshrfeltop',1,'']]],
  ['signaltype_10',['SignalType',['../r1cs-backend.html#signaltype',1,'']]],
  ['sintdiv_20_3a_3allzk_3a_3afelt_3a_3asignedintdivfeltop_11',['&lt;span class=&quot;tt&quot;&gt;felt.sintdiv&lt;/span&gt; (llzk::felt::SignedIntDivFeltOp)',['../dialects.html#feltsintdiv-llzkfeltsignedintdivfeltop',1,'']]],
  ['site_20organization_12',['Site Organization',['../index.html#site-organization',1,'']]],
  ['size_13',['&lt;span class=&quot;tt&quot;&gt;-pcl-trim-expression-size&lt;/span&gt;',['../tools.html#autotoc_md-pcl-trim-expression-size',1,'']]],
  ['smod_20_3a_3allzk_3a_3afelt_3a_3asignedmodfeltop_14',['&lt;span class=&quot;tt&quot;&gt;felt.smod&lt;/span&gt; (llzk::felt::SignedModFeltOp)',['../dialects.html#feltsmod-llzkfeltsignedmodfeltop',1,'']]],
  ['smt_20backend_15',['SMT Backend',['../smt-backend.html',1,'backends-page']]],
  ['smt_20check_16',['llzk-smt-check',['../tools.html#llzk-smt-check',1,'']]],
  ['smt_5finfo_20dialect_17',['&apos;smt_info&apos; Dialect',['../smt-backend.html#smt_info-dialect',1,'']]],
  ['smt_5finfo_20set_20_3a_3allzk_3a_3asmt_5finfo_3a_3asmtinfosetop_18',['&lt;span class=&quot;tt&quot;&gt;smt_info.set&lt;/span&gt; (llzk::smt_info::SMTInfoSetOp)',['../smt-backend.html#smt_infoset-llzksmt_infosmtinfosetop',1,'']]],
  ['solve_20an_20issue_19',['Solve an issue',['../contribution-guide.html#solve-an-issue',1,'']]],
  ['specialize_20wildcard_20arrays_20',['&lt;span class=&quot;tt&quot;&gt;-llzk-specialize-wildcard-arrays&lt;/span&gt;',['../tools.html#autotoc_md-llzk-specialize-wildcard-arrays',1,'']]],
  ['specific_20options_21',['Specific Options',['../tools.html#llzk-specific-options',1,'LLZK-Specific Options'],['../tools.html#llzk-specific-options-1',1,'LLZK-Specific Options'],['../tools.html#llzk-specific-options-2',1,'LLZK-Specific Options'],['../tools.html#llzk-specific-options-3',1,'LLZK-Specific Options']]],
  ['specification_22',['LLZK Language Specification',['../syntax.html',1,'']]],
  ['standards_23',['Our Standards',['../code-of-conduct.html#our-standards',1,'']]],
  ['started_24',['Getting started',['../contribution-guide.html#getting-started',1,'']]],
  ['static_20array_20promotion_25',['&lt;span class=&quot;tt&quot;&gt;-llzk-straight-line-static-array-promotion&lt;/span&gt;',['../tools.html#autotoc_md-llzk-straight-line-static-array-promotion',1,'']]],
  ['straight_20line_20static_20array_20promotion_26',['&lt;span class=&quot;tt&quot;&gt;-llzk-straight-line-static-array-promotion&lt;/span&gt;',['../tools.html#autotoc_md-llzk-straight-line-static-array-promotion',1,'']]],
  ['string_20dialect_27',['&apos;string&apos; Dialect',['../dialects.html#string-dialect',1,'']]],
  ['string_20new_20_3a_3allzk_3a_3astring_3a_3alitstringop_28',['&lt;span class=&quot;tt&quot;&gt;string.new&lt;/span&gt; (llzk::string::LitStringOp)',['../dialects.html#stringnew-llzkstringlitstringop',1,'']]],
  ['stringtype_29',['StringType',['../dialects.html#stringtype',1,'']]],
  ['struct_20def_20_3a_3allzk_3a_3acomponent_3a_3astructdefop_30',['&lt;span class=&quot;tt&quot;&gt;struct.def&lt;/span&gt; (llzk::component::StructDefOp)',['../dialects.html#structdef-llzkcomponentstructdefop',1,'']]],
  ['struct_20dialect_31',['&apos;struct&apos; Dialect',['../dialects.html#struct-dialect',1,'']]],
  ['struct_20inlining_32',['&lt;span class=&quot;tt&quot;&gt;-llzk-full-struct-inlining&lt;/span&gt;',['../tools.html#autotoc_md-llzk-full-struct-inlining',1,'']]],
  ['struct_20member_20_3a_3allzk_3a_3acomponent_3a_3amemberdefop_33',['&lt;span class=&quot;tt&quot;&gt;struct.member&lt;/span&gt; (llzk::component::MemberDefOp)',['../dialects.html#structmember-llzkcomponentmemberdefop',1,'']]],
  ['struct_20new_20_3a_3allzk_3a_3acomponent_3a_3acreatestructop_34',['&lt;span class=&quot;tt&quot;&gt;struct.new&lt;/span&gt; (llzk::component::CreateStructOp)',['../dialects.html#structnew-llzkcomponentcreatestructop',1,'']]],
  ['struct_20readm_20_3a_3allzk_3a_3acomponent_3a_3amemberreadop_35',['&lt;span class=&quot;tt&quot;&gt;struct.readm&lt;/span&gt; (llzk::component::MemberReadOp)',['../dialects.html#structreadm-llzkcomponentmemberreadop',1,'']]],
  ['struct_20writem_20_3a_3allzk_3a_3acomponent_3a_3amemberwriteop_36',['&lt;span class=&quot;tt&quot;&gt;struct.writem&lt;/span&gt; (llzk::component::MemberWriteOp)',['../dialects.html#structwritem-llzkcomponentmemberwriteop',1,'']]],
  ['structs_37',['&lt;span class=&quot;tt&quot;&gt;-llzk-inline-structs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-inline-structs',1,'']]],
  ['structtype_38',['StructType',['../dialects.html#structtype',1,'StructType'],['../zklean-backend.html#structtype-1',1,'StructType']]],
  ['structure_20_3a_3allzk_3a_3azkleanlean_3a_3astructdefop_39',['&lt;span class=&quot;tt&quot;&gt;ZKLeanLean.structure&lt;/span&gt; (llzk::zkleanlean::StructDefOp)',['../zklean-backend.html#zkleanleanstructure-llzkzkleanleanstructdefop',1,'']]],
  ['sub_20_3a_3allzk_3a_3afelt_3a_3asubfeltop_40',['&lt;span class=&quot;tt&quot;&gt;felt.sub&lt;/span&gt; (llzk::felt::SubFeltOp)',['../dialects.html#feltsub-llzkfeltsubfeltop',1,'']]],
  ['sub_20_3a_3allzk_3a_3azkexpr_3a_3asubop_41',['&lt;span class=&quot;tt&quot;&gt;ZKExpr.Sub&lt;/span&gt; (llzk::zkexpr::SubOp)',['../zklean-backend.html#zkexprsub-llzkzkexprsubop',1,'']]],
  ['sub_20_3a_3apcl_3a_3asubop_42',['&lt;span class=&quot;tt&quot;&gt;pcl.sub&lt;/span&gt; (pcl::SubOp)',['../pcl-backend.html#pclsub-pclsubop',1,'']]],
  ['symbol_20def_20tree_43',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-symbol-def-tree&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-symbol-def-tree',1,'']]],
  ['symbol_20use_20graph_44',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-symbol-use-graph&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-symbol-use-graph',1,'']]],
  ['symbolattr_45',['SymbolAttr',['../smt-backend.html#symbolattr',1,'']]],
  ['syntax_46',['Syntax',['../syntax.html#syntax-1',1,'']]]
];
