var searchData=
[
  ['param_20_3a_3allzk_3a_3apolymorphic_3a_3atemplateparamop_0',['&lt;span class=&quot;tt&quot;&gt;poly.param&lt;/span&gt; (llzk::polymorphic::TemplateParamOp)',['../dialects.html#polyparam-llzkpolymorphictemplateparamop',1,'']]],
  ['parameters_3a_1',['Parameters:',['../dialects.html#parameters',1,'Parameters:'],['../dialects.html#parameters-1',1,'Parameters:'],['../dialects.html#parameters-2',1,'Parameters:'],['../dialects.html#parameters-3',1,'Parameters:'],['../dialects.html#parameters-4',1,'Parameters:'],['../dialects.html#parameters-5',1,'Parameters:'],['../dialects.html#parameters-6',1,'Parameters:'],['../dialects.html#parameters-7',1,'Parameters:'],['../dialects.html#parameters-8',1,'Parameters:'],['../dialects.html#parameters-9',1,'Parameters:'],['../dialects.html#parameters-10',1,'Parameters:'],['../r1cs-backend.html#parameters-11',1,'Parameters:'],['../smt-backend.html#parameters-12',1,'Parameters:'],['../smt-backend.html#parameters-13',1,'Parameters:'],['../smt-backend.html#parameters-14',1,'Parameters:'],['../smt-backend.html#parameters-15',1,'Parameters:'],['../smt-backend.html#parameters-16',1,'Parameters:'],['../smt-backend.html#parameters-17',1,'Parameters:'],['../smt-backend.html#parameters-18',1,'Parameters:'],['../pcl-backend.html#parameters-19',1,'Parameters:'],['../pcl-backend.html#parameters-20',1,'Parameters:'],['../pcl-backend.html#parameters-21',1,'Parameters:'],['../zklean-backend.html#parameters-22',1,'Parameters:'],['../zklean-backend.html#parameters-23',1,'Parameters:']]],
  ['pass_2',['&lt;span class=&quot;tt&quot;&gt;-llzk-poly-lowering-pass&lt;/span&gt;',['../tools.html#autotoc_md-llzk-poly-lowering-pass',1,'']]],
  ['pass_20documentation_3',['LLZK Pass Documentation',['../tools.html#passes',1,'']]],
  ['passes_4',['Passes',['../tools.html#analysis-passes',1,'Analysis Passes'],['../overview.html#pass-overview',1,'Passes'],['../tools.html#transformation-passes',1,'Transformation Passes'],['../tools.html#validation-passes',1,'Validation Passes']]],
  ['patches_5',['Patches',['../maintanence.html#patches',1,'']]],
  ['pcl_6',['&lt;span class=&quot;tt&quot;&gt;-llzk-to-pcl&lt;/span&gt;',['../tools.html#autotoc_md-llzk-to-pcl',1,'']]],
  ['pcl_20add_20_3a_3apcl_3a_3aaddop_7',['&lt;span class=&quot;tt&quot;&gt;pcl.add&lt;/span&gt; (pcl::AddOp)',['../pcl-backend.html#pcladd-pcladdop',1,'']]],
  ['pcl_20and_20_3a_3apcl_3a_3aandop_8',['&lt;span class=&quot;tt&quot;&gt;pcl.and&lt;/span&gt; (pcl::AndOp)',['../pcl-backend.html#pcland-pclandop',1,'']]],
  ['pcl_20asfelt_20_3a_3apcl_3a_3aasfeltop_9',['&lt;span class=&quot;tt&quot;&gt;pcl.asfelt&lt;/span&gt; (pcl::AsFeltOp)',['../pcl-backend.html#pclasfelt-pclasfeltop',1,'']]],
  ['pcl_20assert_20_3a_3apcl_3a_3aassertop_10',['&lt;span class=&quot;tt&quot;&gt;pcl.assert&lt;/span&gt; (pcl::AssertOp)',['../pcl-backend.html#pclassert-pclassertop',1,'']]],
  ['pcl_20assume_20deterministic_20_3a_3apcl_3a_3aassumedeterministicop_11',['&lt;span class=&quot;tt&quot;&gt;pcl.assume.deterministic&lt;/span&gt; (pcl::AssumeDeterministicOp)',['../pcl-backend.html#pclassumedeterministic-pclassumedeterministicop',1,'']]],
  ['pcl_20backend_12',['PCL Backend',['../pcl-backend.html',1,'backends-page']]],
  ['pcl_20const_20_3a_3apcl_3a_3aconstop_13',['&lt;span class=&quot;tt&quot;&gt;pcl.const&lt;/span&gt; (pcl::ConstOp)',['../pcl-backend.html#pclconst-pclconstop',1,'']]],
  ['pcl_20det_20_3a_3apcl_3a_3adetop_14',['&lt;span class=&quot;tt&quot;&gt;pcl.det&lt;/span&gt; (pcl::DetOp)',['../pcl-backend.html#pcldet-pcldetop',1,'']]],
  ['pcl_20dialect_15',['&apos;pcl&apos; Dialect',['../pcl-backend.html#pcl-dialect',1,'']]],
  ['pcl_20eq_20_3a_3apcl_3a_3acmpeqop_16',['&lt;span class=&quot;tt&quot;&gt;pcl.eq&lt;/span&gt; (pcl::CmpEqOp)',['../pcl-backend.html#pcleq-pclcmpeqop',1,'']]],
  ['pcl_20false_20_3a_3apcl_3a_3afalseop_17',['&lt;span class=&quot;tt&quot;&gt;pcl.false&lt;/span&gt; (pcl::FalseOp)',['../pcl-backend.html#pclfalse-pclfalseop',1,'']]],
  ['pcl_20ge_20_3a_3apcl_3a_3acmpgeop_18',['&lt;span class=&quot;tt&quot;&gt;pcl.ge&lt;/span&gt; (pcl::CmpGeOp)',['../pcl-backend.html#pclge-pclcmpgeop',1,'']]],
  ['pcl_20gt_20_3a_3apcl_3a_3acmpgtop_19',['&lt;span class=&quot;tt&quot;&gt;pcl.gt&lt;/span&gt; (pcl::CmpGtOp)',['../pcl-backend.html#pclgt-pclcmpgtop',1,'']]],
  ['pcl_20iff_20_3a_3apcl_3a_3aiffop_20',['&lt;span class=&quot;tt&quot;&gt;pcl.iff&lt;/span&gt; (pcl::IffOp)',['../pcl-backend.html#pcliff-pcliffop',1,'']]],
  ['pcl_20implies_20_3a_3apcl_3a_3aimpliesop_21',['&lt;span class=&quot;tt&quot;&gt;pcl.implies&lt;/span&gt; (pcl::ImpliesOp)',['../pcl-backend.html#pclimplies-pclimpliesop',1,'']]],
  ['pcl_20le_20_3a_3apcl_3a_3acmpleop_22',['&lt;span class=&quot;tt&quot;&gt;pcl.le&lt;/span&gt; (pcl::CmpLeOp)',['../pcl-backend.html#pclle-pclcmpleop',1,'']]],
  ['pcl_20lt_20_3a_3apcl_3a_3acmpltop_23',['&lt;span class=&quot;tt&quot;&gt;pcl.lt&lt;/span&gt; (pcl::CmpLtOp)',['../pcl-backend.html#pcllt-pclcmpltop',1,'']]],
  ['pcl_20mul_20_3a_3apcl_3a_3amulop_24',['&lt;span class=&quot;tt&quot;&gt;pcl.mul&lt;/span&gt; (pcl::MulOp)',['../pcl-backend.html#pclmul-pclmulop',1,'']]],
  ['pcl_20neg_20_3a_3apcl_3a_3anegop_25',['&lt;span class=&quot;tt&quot;&gt;pcl.neg&lt;/span&gt; (pcl::NegOp)',['../pcl-backend.html#pclneg-pclnegop',1,'']]],
  ['pcl_20not_20_3a_3apcl_3a_3anotop_26',['&lt;span class=&quot;tt&quot;&gt;pcl.not&lt;/span&gt; (pcl::NotOp)',['../pcl-backend.html#pclnot-pclnotop',1,'']]],
  ['pcl_20or_20_3a_3apcl_3a_3aorop_27',['&lt;span class=&quot;tt&quot;&gt;pcl.or&lt;/span&gt; (pcl::OrOp)',['../pcl-backend.html#pclor-pclorop',1,'']]],
  ['pcl_20post_5fcond_20_3a_3apcl_3a_3apostop_28',['&lt;span class=&quot;tt&quot;&gt;pcl.post_cond&lt;/span&gt; (pcl::PostOp)',['../pcl-backend.html#pclpost_cond-pclpostop',1,'']]],
  ['pcl_20sub_20_3a_3apcl_3a_3asubop_29',['&lt;span class=&quot;tt&quot;&gt;pcl.sub&lt;/span&gt; (pcl::SubOp)',['../pcl-backend.html#pclsub-pclsubop',1,'']]],
  ['pcl_20trim_20expression_20size_30',['&lt;span class=&quot;tt&quot;&gt;-pcl-trim-expression-size&lt;/span&gt;',['../tools.html#autotoc_md-pcl-trim-expression-size',1,'']]],
  ['pcl_20true_20_3a_3apcl_3a_3atrueop_31',['&lt;span class=&quot;tt&quot;&gt;pcl.true&lt;/span&gt; (pcl::TrueOp)',['../pcl-backend.html#pcltrue-pcltrueop',1,'']]],
  ['pcl_20var_20_3a_3apcl_3a_3avarop_32',['&lt;span class=&quot;tt&quot;&gt;pcl.var&lt;/span&gt; (pcl::VarOp)',['../pcl-backend.html#pclvar-pclvarop',1,'']]],
  ['permanent_20ban_33',['4. Permanent Ban',['../code-of-conduct.html#autotoc_md4-permanent-ban',1,'']]],
  ['philosophy_34',['Contribution Philosophy',['../contribution-guide.html#contribution-philosophy',1,'']]],
  ['pipelines_35',['Predefined Pipelines',['../tools.html#predefined-pipelines',1,'']]],
  ['pledge_36',['Our Pledge',['../code-of-conduct.html#our-pledge',1,'']]],
  ['pod_20dialect_37',['&apos;pod&apos; Dialect',['../dialects.html#pod-dialect',1,'']]],
  ['pod_20new_20_3a_3allzk_3a_3apod_3a_3anewpodop_38',['&lt;span class=&quot;tt&quot;&gt;pod.new&lt;/span&gt; (llzk::pod::NewPodOp)',['../dialects.html#podnew-llzkpodnewpodop',1,'']]],
  ['pod_20read_20_3a_3allzk_3a_3apod_3a_3areadpodop_39',['&lt;span class=&quot;tt&quot;&gt;pod.read&lt;/span&gt; (llzk::pod::ReadPodOp)',['../dialects.html#podread-llzkpodreadpodop',1,'']]],
  ['pod_20to_20scalar_40',['&lt;span class=&quot;tt&quot;&gt;-llzk-pod-to-scalar&lt;/span&gt;',['../tools.html#autotoc_md-llzk-pod-to-scalar',1,'']]],
  ['pod_20write_20_3a_3allzk_3a_3apod_3a_3awritepodop_41',['&lt;span class=&quot;tt&quot;&gt;pod.write&lt;/span&gt; (llzk::pod::WritePodOp)',['../dialects.html#podwrite-llzkpodwritepodop',1,'']]],
  ['podtype_42',['PodType',['../dialects.html#podtype',1,'']]],
  ['poly_20applymap_20_3a_3allzk_3a_3apolymorphic_3a_3aapplymapop_43',['&lt;span class=&quot;tt&quot;&gt;poly.applymap&lt;/span&gt; (llzk::polymorphic::ApplyMapOp)',['../dialects.html#polyapplymap-llzkpolymorphicapplymapop',1,'']]],
  ['poly_20dialect_44',['&apos;poly&apos; Dialect',['../dialects.html#poly-dialect',1,'']]],
  ['poly_20expr_20_3a_3allzk_3a_3apolymorphic_3a_3atemplateexprop_45',['&lt;span class=&quot;tt&quot;&gt;poly.expr&lt;/span&gt; (llzk::polymorphic::TemplateExprOp)',['../dialects.html#polyexpr-llzkpolymorphictemplateexprop',1,'']]],
  ['poly_20lowering_46',['&lt;span class=&quot;tt&quot;&gt;-llzk-full-poly-lowering&lt;/span&gt;',['../tools.html#autotoc_md-llzk-full-poly-lowering',1,'']]],
  ['poly_20lowering_20pass_47',['&lt;span class=&quot;tt&quot;&gt;-llzk-poly-lowering-pass&lt;/span&gt;',['../tools.html#autotoc_md-llzk-poly-lowering-pass',1,'']]],
  ['poly_20param_20_3a_3allzk_3a_3apolymorphic_3a_3atemplateparamop_48',['&lt;span class=&quot;tt&quot;&gt;poly.param&lt;/span&gt; (llzk::polymorphic::TemplateParamOp)',['../dialects.html#polyparam-llzkpolymorphictemplateparamop',1,'']]],
  ['poly_20read_5fconst_20_3a_3allzk_3a_3apolymorphic_3a_3aconstreadop_49',['&lt;span class=&quot;tt&quot;&gt;poly.read_const&lt;/span&gt; (llzk::polymorphic::ConstReadOp)',['../dialects.html#polyread_const-llzkpolymorphicconstreadop',1,'']]],
  ['poly_20template_20_3a_3allzk_3a_3apolymorphic_3a_3atemplateop_50',['&lt;span class=&quot;tt&quot;&gt;poly.template&lt;/span&gt; (llzk::polymorphic::TemplateOp)',['../dialects.html#polytemplate-llzkpolymorphictemplateop',1,'']]],
  ['poly_20unifiable_5fcast_20_3a_3allzk_3a_3apolymorphic_3a_3aunifiablecastop_51',['&lt;span class=&quot;tt&quot;&gt;poly.unifiable_cast&lt;/span&gt; (llzk::polymorphic::UnifiableCastOp)',['../dialects.html#polyunifiable_cast-llzkpolymorphicunifiablecastop',1,'']]],
  ['poly_20yield_20_3a_3allzk_3a_3apolymorphic_3a_3ayieldop_52',['&lt;span class=&quot;tt&quot;&gt;poly.yield&lt;/span&gt; (llzk::polymorphic::YieldOp)',['../dialects.html#polyyield-llzkpolymorphicyieldop',1,'']]],
  ['pop_20_3a_3allzk_3a_3asmt_3a_3apopop_53',['&lt;span class=&quot;tt&quot;&gt;smt.pop&lt;/span&gt; (llzk::smt::PopOp)',['../smt-backend.html#smtpop-llzksmtpopop',1,'']]],
  ['post_5fcond_20_3a_3apcl_3a_3apostop_54',['&lt;span class=&quot;tt&quot;&gt;pcl.post_cond&lt;/span&gt; (pcl::PostOp)',['../pcl-backend.html#pclpost_cond-pclpostop',1,'']]],
  ['pow_20_3a_3allzk_3a_3afelt_3a_3apowfeltop_55',['&lt;span class=&quot;tt&quot;&gt;felt.pow&lt;/span&gt; (llzk::felt::PowFeltOp)',['../dialects.html#feltpow-llzkfeltpowfeltop',1,'']]],
  ['pr_20is_20merged_56',['Your PR is merged!',['../contribution-guide.html#your-pr-is-merged',1,'']]],
  ['practices_20checklist_57',['Best Practices Checklist',['../contribution-guide.html#best-practices-checklist',1,'']]],
  ['predecessors_58',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-predecessors&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-predecessors',1,'']]],
  ['predefined_20pipelines_59',['Predefined Pipelines',['../tools.html#predefined-pipelines',1,'']]],
  ['preparing_20a_20new_20release_60',['Preparing a new release',['../maintanence.html#preparing-a-new-release',1,'']]],
  ['preprocessing_61',['Preprocessing',['../tools.html#preprocessing',1,'']]],
  ['primeattr_62',['PrimeAttr',['../pcl-backend.html#primeattr',1,'']]],
  ['print_20call_20graph_63',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-call-graph&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-call-graph',1,'']]],
  ['print_20call_20graph_20sccs_64',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-call-graph-sccs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-call-graph-sccs',1,'']]],
  ['print_20constraint_20dependency_20graphs_65',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-constraint-dependency-graphs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-constraint-dependency-graphs',1,'']]],
  ['print_20interval_20analysis_66',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-interval-analysis&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-interval-analysis',1,'']]],
  ['print_20predecessors_67',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-predecessors&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-predecessors',1,'']]],
  ['print_20symbol_20def_20tree_68',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-symbol-def-tree&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-symbol-def-tree',1,'']]],
  ['print_20symbol_20use_20graph_69',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-symbol-use-graph&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-symbol-use-graph',1,'']]],
  ['product_70',['&lt;span class=&quot;tt&quot;&gt;-llzk-compute-constrain-to-product&lt;/span&gt;',['../tools.html#autotoc_md-llzk-compute-constrain-to-product',1,'']]],
  ['product_20control_20flow_71',['&lt;span class=&quot;tt&quot;&gt;-llzk-fuse-product-control-flow&lt;/span&gt;',['../tools.html#autotoc_md-llzk-fuse-product-control-flow',1,'']]],
  ['product_20program_72',['&lt;span class=&quot;tt&quot;&gt;-llzk-product-program&lt;/span&gt;',['../tools.html#autotoc_md-llzk-product-program',1,'']]],
  ['program_73',['&lt;span class=&quot;tt&quot;&gt;-llzk-product-program&lt;/span&gt;',['../tools.html#autotoc_md-llzk-product-program',1,'']]],
  ['project_20overview_74',['Project Overview',['../overview.html#project-overview',1,'']]],
  ['pseudo_20homogeneous_20arrays_75',['Pseudo-homogeneous arrays',['../syntax.html#pseudo-homogeneous',1,'']]],
  ['publicattr_76',['PublicAttr',['../dialects.html#publicattr',1,'PublicAttr'],['../r1cs-backend.html#publicattr-1',1,'PublicAttr']]],
  ['pull_20request_77',['Pull Request',['../contribution-guide.html#pull-request',1,'']]],
  ['pull_20request_20review_78',['Pull Request Review',['../contribution-guide.html#pull-request-review',1,'']]],
  ['push_20_3a_3allzk_3a_3asmt_3a_3apushop_79',['&lt;span class=&quot;tt&quot;&gt;smt.push&lt;/span&gt; (llzk::smt::PushOp)',['../smt-backend.html#smtpush-llzksmtpushop',1,'']]]
];
