var searchData=
[
  ['language_20specification_0',['LLZK Language Specification',['../syntax.html',1,'']]],
  ['le_20_3a_3apcl_3a_3acmpleop_1',['&lt;span class=&quot;tt&quot;&gt;pcl.le&lt;/span&gt; (pcl::CmpLeOp)',['../pcl-backend.html#pclle-pclcmpleop',1,'']]],
  ['len_20_3a_3allzk_3a_3aarray_3a_3aarraylengthop_2',['&lt;span class=&quot;tt&quot;&gt;array.len&lt;/span&gt; (llzk::array::ArrayLengthOp)',['../dialects.html#arraylen-llzkarrayarraylengthop',1,'']]],
  ['license_3',['LLZK License',['../license.html',1,'index']]],
  ['lineartype_4',['LinearType',['../r1cs-backend.html#lineartype',1,'']]],
  ['list_5',['Todo List',['../todo.html',1,'']]],
  ['literal_20_3a_3allzk_3a_3azkexpr_3a_3aliteralop_6',['&lt;span class=&quot;tt&quot;&gt;ZKExpr.Literal&lt;/span&gt; (llzk::zkexpr::LiteralOp)',['../zklean-backend.html#zkexprliteral-llzkzkexprliteralop',1,'']]],
  ['llzk_20array_20to_20scalar_7',['&lt;span class=&quot;tt&quot;&gt;-llzk-array-to-scalar&lt;/span&gt;',['../tools.html#autotoc_md-llzk-array-to-scalar',1,'']]],
  ['llzk_20compute_20constrain_20to_20product_8',['&lt;span class=&quot;tt&quot;&gt;-llzk-compute-constrain-to-product&lt;/span&gt;',['../tools.html#autotoc_md-llzk-compute-constrain-to-product',1,'']]],
  ['llzk_20dialect_9',['&apos;llzk&apos; Dialect',['../dialects.html#llzk-dialect',1,'']]],
  ['llzk_20drop_20empty_20templates_10',['&lt;span class=&quot;tt&quot;&gt;-llzk-drop-empty-templates&lt;/span&gt;',['../tools.html#autotoc_md-llzk-drop-empty-templates',1,'']]],
  ['llzk_20duplicate_20op_20elim_11',['&lt;span class=&quot;tt&quot;&gt;-llzk-duplicate-op-elim&lt;/span&gt;',['../tools.html#autotoc_md-llzk-duplicate-op-elim',1,'']]],
  ['llzk_20duplicate_20read_20write_20elim_12',['&lt;span class=&quot;tt&quot;&gt;-llzk-duplicate-read-write-elim&lt;/span&gt;',['../tools.html#autotoc_md-llzk-duplicate-read-write-elim',1,'']]],
  ['llzk_20enforce_20no_20overwrite_13',['&lt;span class=&quot;tt&quot;&gt;-llzk-enforce-no-overwrite&lt;/span&gt;',['../tools.html#autotoc_md-llzk-enforce-no-overwrite',1,'']]],
  ['llzk_20flatten_14',['&lt;span class=&quot;tt&quot;&gt;-llzk-flatten&lt;/span&gt;',['../tools.html#autotoc_md-llzk-flatten',1,'']]],
  ['llzk_20full_20inlining_15',['&lt;span class=&quot;tt&quot;&gt;-llzk-full-inlining&lt;/span&gt;',['../tools.html#autotoc_md-llzk-full-inlining',1,'']]],
  ['llzk_20full_20poly_20lowering_16',['&lt;span class=&quot;tt&quot;&gt;-llzk-full-poly-lowering&lt;/span&gt;',['../tools.html#autotoc_md-llzk-full-poly-lowering',1,'']]],
  ['llzk_20full_20r1cs_20lowering_17',['&lt;span class=&quot;tt&quot;&gt;-llzk-full-r1cs-lowering&lt;/span&gt;',['../tools.html#autotoc_md-llzk-full-r1cs-lowering',1,'']]],
  ['llzk_20full_20struct_20inlining_18',['&lt;span class=&quot;tt&quot;&gt;-llzk-full-struct-inlining&lt;/span&gt;',['../tools.html#autotoc_md-llzk-full-struct-inlining',1,'']]],
  ['llzk_20fuse_20product_20control_20flow_19',['&lt;span class=&quot;tt&quot;&gt;-llzk-fuse-product-control-flow&lt;/span&gt;',['../tools.html#autotoc_md-llzk-fuse-product-control-flow',1,'']]],
  ['llzk_20infer_20tvar_20',['&lt;span class=&quot;tt&quot;&gt;-llzk-infer-tvar&lt;/span&gt;',['../tools.html#autotoc_md-llzk-infer-tvar',1,'']]],
  ['llzk_20inline_20free_20functions_21',['&lt;span class=&quot;tt&quot;&gt;-llzk-inline-free-functions&lt;/span&gt;',['../tools.html#autotoc_md-llzk-inline-free-functions',1,'']]],
  ['llzk_20inline_20includes_22',['&lt;span class=&quot;tt&quot;&gt;-llzk-inline-includes&lt;/span&gt;',['../tools.html#autotoc_md-llzk-inline-includes',1,'']]],
  ['llzk_20inline_20structs_23',['&lt;span class=&quot;tt&quot;&gt;-llzk-inline-structs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-inline-structs',1,'']]],
  ['llzk_20ir_20dialects_24',['LLZK IR Dialects',['../dialects.html',1,'LLZK IR Dialects'],['../overview.html#llzk-ir-dialects',1,'LLZK IR Dialects']]],
  ['llzk_20language_20specification_25',['LLZK Language Specification',['../syntax.html',1,'']]],
  ['llzk_20license_26',['LLZK License',['../license.html',1,'index']]],
  ['llzk_20lower_20bool_20quantifiers_27',['&lt;span class=&quot;tt&quot;&gt;-llzk-lower-bool-quantifiers&lt;/span&gt;',['../tools.html#autotoc_md-llzk-lower-bool-quantifiers',1,'']]],
  ['llzk_20lsp_20server_28',['llzk-lsp-server',['../tools.html#llzk-lsp-server',1,'']]],
  ['llzk_20nondet_20_3a_3allzk_3a_3anondetop_29',['&lt;span class=&quot;tt&quot;&gt;llzk.nondet&lt;/span&gt; (llzk::NonDetOp)',['../dialects.html#llzknondet-llzknondetop',1,'']]],
  ['llzk_20opt_30',['llzk-opt',['../tools.html#llzk-opt',1,'']]],
  ['llzk_20pass_20documentation_31',['LLZK Pass Documentation',['../tools.html#passes',1,'']]],
  ['llzk_20pod_20to_20scalar_32',['&lt;span class=&quot;tt&quot;&gt;-llzk-pod-to-scalar&lt;/span&gt;',['../tools.html#autotoc_md-llzk-pod-to-scalar',1,'']]],
  ['llzk_20poly_20lowering_20pass_33',['&lt;span class=&quot;tt&quot;&gt;-llzk-poly-lowering-pass&lt;/span&gt;',['../tools.html#autotoc_md-llzk-poly-lowering-pass',1,'']]],
  ['llzk_20print_20call_20graph_34',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-call-graph&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-call-graph',1,'']]],
  ['llzk_20print_20call_20graph_20sccs_35',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-call-graph-sccs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-call-graph-sccs',1,'']]],
  ['llzk_20print_20constraint_20dependency_20graphs_36',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-constraint-dependency-graphs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-constraint-dependency-graphs',1,'']]],
  ['llzk_20print_20interval_20analysis_37',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-interval-analysis&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-interval-analysis',1,'']]],
  ['llzk_20print_20predecessors_38',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-predecessors&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-predecessors',1,'']]],
  ['llzk_20print_20symbol_20def_20tree_39',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-symbol-def-tree&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-symbol-def-tree',1,'']]],
  ['llzk_20print_20symbol_20use_20graph_40',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-symbol-use-graph&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-symbol-use-graph',1,'']]],
  ['llzk_20product_20program_41',['&lt;span class=&quot;tt&quot;&gt;-llzk-product-program&lt;/span&gt;',['../tools.html#autotoc_md-llzk-product-program',1,'']]],
  ['llzk_20r1cs_20lowering_42',['&lt;span class=&quot;tt&quot;&gt;-llzk-r1cs-lowering&lt;/span&gt;',['../tools.html#autotoc_md-llzk-r1cs-lowering',1,'']]],
  ['llzk_20remove_20unnecessary_20ops_43',['&lt;span class=&quot;tt&quot;&gt;-llzk-remove-unnecessary-ops&lt;/span&gt;',['../tools.html#autotoc_md-llzk-remove-unnecessary-ops',1,'']]],
  ['llzk_20remove_20unnecessary_20ops_20and_20defs_44',['&lt;span class=&quot;tt&quot;&gt;-llzk-remove-unnecessary-ops-and-defs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-remove-unnecessary-ops-and-defs',1,'']]],
  ['llzk_20remove_20unused_20discardable_20allocations_45',['&lt;span class=&quot;tt&quot;&gt;-llzk-remove-unused-discardable-allocations&lt;/span&gt;',['../tools.html#autotoc_md-llzk-remove-unused-discardable-allocations',1,'']]],
  ['llzk_20smt_20check_46',['llzk-smt-check',['../tools.html#llzk-smt-check',1,'']]],
  ['llzk_20specialize_20wildcard_20arrays_47',['&lt;span class=&quot;tt&quot;&gt;-llzk-specialize-wildcard-arrays&lt;/span&gt;',['../tools.html#autotoc_md-llzk-specialize-wildcard-arrays',1,'']]],
  ['llzk_20specific_20options_48',['LLZK Specific Options',['../tools.html#llzk-specific-options',1,'LLZK-Specific Options'],['../tools.html#llzk-specific-options-1',1,'LLZK-Specific Options'],['../tools.html#llzk-specific-options-2',1,'LLZK-Specific Options'],['../tools.html#llzk-specific-options-3',1,'LLZK-Specific Options']]],
  ['llzk_20to_20pcl_49',['&lt;span class=&quot;tt&quot;&gt;-llzk-to-pcl&lt;/span&gt;',['../tools.html#autotoc_md-llzk-to-pcl',1,'']]],
  ['llzk_20translate_50',['llzk-translate',['../tools.html#llzk-translate',1,'']]],
  ['llzk_20unused_20declaration_20elim_51',['&lt;span class=&quot;tt&quot;&gt;-llzk-unused-declaration-elim&lt;/span&gt;',['../tools.html#autotoc_md-llzk-unused-declaration-elim',1,'']]],
  ['llzk_20validate_20member_20writes_52',['&lt;span class=&quot;tt&quot;&gt;-llzk-validate-member-writes&lt;/span&gt;',['../tools.html#autotoc_md-llzk-validate-member-writes',1,'']]],
  ['llzk_20while_20to_20for_53',['&lt;span class=&quot;tt&quot;&gt;-llzk-while-to-for&lt;/span&gt;',['../tools.html#autotoc_md-llzk-while-to-for',1,'']]],
  ['llzk_20witgen_54',['llzk-witgen',['../tools.html#llzk-witgen',1,'']]],
  ['loopboundsattr_55',['LoopBoundsAttr',['../dialects.html#loopboundsattr',1,'']]],
  ['lower_20bool_20quantifiers_56',['&lt;span class=&quot;tt&quot;&gt;-llzk-lower-bool-quantifiers&lt;/span&gt;',['../tools.html#autotoc_md-llzk-lower-bool-quantifiers',1,'']]],
  ['lowering_57',['lowering',['../tools.html#autotoc_md-llzk-full-poly-lowering',1,'&lt;span class=&quot;tt&quot;&gt;-llzk-full-poly-lowering&lt;/span&gt;'],['../tools.html#autotoc_md-llzk-full-r1cs-lowering',1,'&lt;span class=&quot;tt&quot;&gt;-llzk-full-r1cs-lowering&lt;/span&gt;'],['../tools.html#autotoc_md-llzk-r1cs-lowering',1,'&lt;span class=&quot;tt&quot;&gt;-llzk-r1cs-lowering&lt;/span&gt;']]],
  ['lowering_20pass_58',['&lt;span class=&quot;tt&quot;&gt;-llzk-poly-lowering-pass&lt;/span&gt;',['../tools.html#autotoc_md-llzk-poly-lowering-pass',1,'']]],
  ['lshr_20_3a_3allzk_3a_3asmt_3a_3abvlshrop_59',['&lt;span class=&quot;tt&quot;&gt;smt.bv.lshr&lt;/span&gt; (llzk::smt::BVLShrOp)',['../smt-backend.html#smtbvlshr-llzksmtbvlshrop',1,'']]],
  ['lsp_20server_60',['llzk-lsp-server',['../tools.html#llzk-lsp-server',1,'']]],
  ['lt_20_3a_3apcl_3a_3acmpltop_61',['&lt;span class=&quot;tt&quot;&gt;pcl.lt&lt;/span&gt; (pcl::CmpLtOp)',['../pcl-backend.html#pcllt-pclcmpltop',1,'']]]
];
