var searchData=
[
  ['scalar_0',['scalar',['../tools.html#autotoc_md-llzk-array-to-scalar',1,'&lt;span class=&quot;tt&quot;&gt;-llzk-array-to-scalar&lt;/span&gt;'],['../tools.html#autotoc_md-llzk-pod-to-scalar',1,'&lt;span class=&quot;tt&quot;&gt;-llzk-pod-to-scalar&lt;/span&gt;']]],
  ['sccs_1',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-call-graph-sccs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-call-graph-sccs',1,'']]],
  ['schema_2',['File schema',['../md_doc_2doxygen_214__wtns__format.html#file-schema',1,'']]],
  ['scope_3',['Scope',['../code-of-conduct.html#scope',1,'']]],
  ['sdiv_20_3a_3allzk_3a_3asmt_3a_3abvsdivop_4',['&lt;span class=&quot;tt&quot;&gt;smt.bv.sdiv&lt;/span&gt; (llzk::smt::BVSDivOp)',['../smt-backend.html#smtbvsdiv-llzksmtbvsdivop',1,'']]],
  ['select_20_3a_3allzk_3a_3asmt_3a_3aarrayselectop_5',['&lt;span class=&quot;tt&quot;&gt;smt.array.select&lt;/span&gt; (llzk::smt::ArraySelectOp)',['../smt-backend.html#smtarrayselect-llzksmtarrayselectop',1,'']]],
  ['semantic_20rules_6',['Semantic Rules',['../syntax.html#semantic-rules',1,'']]],
  ['server_7',['llzk-lsp-server',['../tools.html#llzk-lsp-server',1,'']]],
  ['set_5finfo_20_3a_3allzk_3a_3asmt_3a_3asetinfoop_8',['&lt;span class=&quot;tt&quot;&gt;smt.set_info&lt;/span&gt; (llzk::smt::SetInfoOp)',['../smt-backend.html#smtset_info-llzksmtsetinfoop',1,'']]],
  ['set_5flogic_20_3a_3allzk_3a_3asmt_3a_3asetlogicop_9',['&lt;span class=&quot;tt&quot;&gt;smt.set_logic&lt;/span&gt; (llzk::smt::SetLogicOp)',['../smt-backend.html#smtset_logic-llzksmtsetlogicop',1,'']]],
  ['setup_10',['Setup',['../setup.html#manual-build-setup',1,'Manual Build Setup'],['../setup.html#nix-setup',1,'Nix Setup'],['../setup.html',1,'Setup']]],
  ['shl_20_3a_3allzk_3a_3afelt_3a_3ashlfeltop_11',['&lt;span class=&quot;tt&quot;&gt;felt.shl&lt;/span&gt; (llzk::felt::ShlFeltOp)',['../dialects.html#feltshl-llzkfeltshlfeltop',1,'']]],
  ['shl_20_3a_3allzk_3a_3asmt_3a_3abvshlop_12',['&lt;span class=&quot;tt&quot;&gt;smt.bv.shl&lt;/span&gt; (llzk::smt::BVShlOp)',['../smt-backend.html#smtbvshl-llzksmtbvshlop',1,'']]],
  ['shr_20_3a_3allzk_3a_3afelt_3a_3ashrfeltop_13',['&lt;span class=&quot;tt&quot;&gt;felt.shr&lt;/span&gt; (llzk::felt::ShrFeltOp)',['../dialects.html#feltshr-llzkfeltshrfeltop',1,'']]],
  ['signaltype_14',['SignalType',['../r1cs-backend.html#signaltype',1,'']]],
  ['sintdiv_20_3a_3allzk_3a_3afelt_3a_3asignedintdivfeltop_15',['&lt;span class=&quot;tt&quot;&gt;felt.sintdiv&lt;/span&gt; (llzk::felt::SignedIntDivFeltOp)',['../dialects.html#feltsintdiv-llzkfeltsignedintdivfeltop',1,'']]],
  ['site_20organization_16',['Site Organization',['../index.html#site-organization',1,'']]],
  ['size_17',['&lt;span class=&quot;tt&quot;&gt;-pcl-trim-expression-size&lt;/span&gt;',['../tools.html#autotoc_md-pcl-trim-expression-size',1,'']]],
  ['smod_20_3a_3allzk_3a_3afelt_3a_3asignedmodfeltop_18',['&lt;span class=&quot;tt&quot;&gt;felt.smod&lt;/span&gt; (llzk::felt::SignedModFeltOp)',['../dialects.html#feltsmod-llzkfeltsignedmodfeltop',1,'']]],
  ['smod_20_3a_3allzk_3a_3asmt_3a_3abvsmodop_19',['&lt;span class=&quot;tt&quot;&gt;smt.bv.smod&lt;/span&gt; (llzk::smt::BVSModOp)',['../smt-backend.html#smtbvsmod-llzksmtbvsmodop',1,'']]],
  ['smt_20and_20_3a_3allzk_3a_3asmt_3a_3aandop_20',['&lt;span class=&quot;tt&quot;&gt;smt.and&lt;/span&gt; (llzk::smt::AndOp)',['../smt-backend.html#smtand-llzksmtandop',1,'']]],
  ['smt_20apply_5ffunc_20_3a_3allzk_3a_3asmt_3a_3aapplyfuncop_21',['&lt;span class=&quot;tt&quot;&gt;smt.apply_func&lt;/span&gt; (llzk::smt::ApplyFuncOp)',['../smt-backend.html#smtapply_func-llzksmtapplyfuncop',1,'']]],
  ['smt_20array_20broadcast_20_3a_3allzk_3a_3asmt_3a_3aarraybroadcastop_22',['&lt;span class=&quot;tt&quot;&gt;smt.array.broadcast&lt;/span&gt; (llzk::smt::ArrayBroadcastOp)',['../smt-backend.html#smtarraybroadcast-llzksmtarraybroadcastop',1,'']]],
  ['smt_20array_20select_20_3a_3allzk_3a_3asmt_3a_3aarrayselectop_23',['&lt;span class=&quot;tt&quot;&gt;smt.array.select&lt;/span&gt; (llzk::smt::ArraySelectOp)',['../smt-backend.html#smtarrayselect-llzksmtarrayselectop',1,'']]],
  ['smt_20array_20store_20_3a_3allzk_3a_3asmt_3a_3aarraystoreop_24',['&lt;span class=&quot;tt&quot;&gt;smt.array.store&lt;/span&gt; (llzk::smt::ArrayStoreOp)',['../smt-backend.html#smtarraystore-llzksmtarraystoreop',1,'']]],
  ['smt_20assert_20_3a_3allzk_3a_3asmt_3a_3aassertop_25',['&lt;span class=&quot;tt&quot;&gt;smt.assert&lt;/span&gt; (llzk::smt::AssertOp)',['../smt-backend.html#smtassert-llzksmtassertop',1,'']]],
  ['smt_20backend_26',['SMT Backend',['../smt-backend.html',1,'backends-page']]],
  ['smt_20bv_20add_20_3a_3allzk_3a_3asmt_3a_3abvaddop_27',['&lt;span class=&quot;tt&quot;&gt;smt.bv.add&lt;/span&gt; (llzk::smt::BVAddOp)',['../smt-backend.html#smtbvadd-llzksmtbvaddop',1,'']]],
  ['smt_20bv_20and_20_3a_3allzk_3a_3asmt_3a_3abvandop_28',['&lt;span class=&quot;tt&quot;&gt;smt.bv.and&lt;/span&gt; (llzk::smt::BVAndOp)',['../smt-backend.html#smtbvand-llzksmtbvandop',1,'']]],
  ['smt_20bv_20ashr_20_3a_3allzk_3a_3asmt_3a_3abvashrop_29',['&lt;span class=&quot;tt&quot;&gt;smt.bv.ashr&lt;/span&gt; (llzk::smt::BVAShrOp)',['../smt-backend.html#smtbvashr-llzksmtbvashrop',1,'']]],
  ['smt_20bv_20cmp_20_3a_3allzk_3a_3asmt_3a_3abvcmpop_30',['&lt;span class=&quot;tt&quot;&gt;smt.bv.cmp&lt;/span&gt; (llzk::smt::BVCmpOp)',['../smt-backend.html#smtbvcmp-llzksmtbvcmpop',1,'']]],
  ['smt_20bv_20concat_20_3a_3allzk_3a_3asmt_3a_3aconcatop_31',['&lt;span class=&quot;tt&quot;&gt;smt.bv.concat&lt;/span&gt; (llzk::smt::ConcatOp)',['../smt-backend.html#smtbvconcat-llzksmtconcatop',1,'']]],
  ['smt_20bv_20constant_20_3a_3allzk_3a_3asmt_3a_3abvconstantop_32',['&lt;span class=&quot;tt&quot;&gt;smt.bv.constant&lt;/span&gt; (llzk::smt::BVConstantOp)',['../smt-backend.html#smtbvconstant-llzksmtbvconstantop',1,'']]],
  ['smt_20bv_20extract_20_3a_3allzk_3a_3asmt_3a_3aextractop_33',['&lt;span class=&quot;tt&quot;&gt;smt.bv.extract&lt;/span&gt; (llzk::smt::ExtractOp)',['../smt-backend.html#smtbvextract-llzksmtextractop',1,'']]],
  ['smt_20bv_20lshr_20_3a_3allzk_3a_3asmt_3a_3abvlshrop_34',['&lt;span class=&quot;tt&quot;&gt;smt.bv.lshr&lt;/span&gt; (llzk::smt::BVLShrOp)',['../smt-backend.html#smtbvlshr-llzksmtbvlshrop',1,'']]],
  ['smt_20bv_20mul_20_3a_3allzk_3a_3asmt_3a_3abvmulop_35',['&lt;span class=&quot;tt&quot;&gt;smt.bv.mul&lt;/span&gt; (llzk::smt::BVMulOp)',['../smt-backend.html#smtbvmul-llzksmtbvmulop',1,'']]],
  ['smt_20bv_20neg_20_3a_3allzk_3a_3asmt_3a_3abvnegop_36',['&lt;span class=&quot;tt&quot;&gt;smt.bv.neg&lt;/span&gt; (llzk::smt::BVNegOp)',['../smt-backend.html#smtbvneg-llzksmtbvnegop',1,'']]],
  ['smt_20bv_20not_20_3a_3allzk_3a_3asmt_3a_3abvnotop_37',['&lt;span class=&quot;tt&quot;&gt;smt.bv.not&lt;/span&gt; (llzk::smt::BVNotOp)',['../smt-backend.html#smtbvnot-llzksmtbvnotop',1,'']]],
  ['smt_20bv_20or_20_3a_3allzk_3a_3asmt_3a_3abvorop_38',['&lt;span class=&quot;tt&quot;&gt;smt.bv.or&lt;/span&gt; (llzk::smt::BVOrOp)',['../smt-backend.html#smtbvor-llzksmtbvorop',1,'']]],
  ['smt_20bv_20repeat_20_3a_3allzk_3a_3asmt_3a_3arepeatop_39',['&lt;span class=&quot;tt&quot;&gt;smt.bv.repeat&lt;/span&gt; (llzk::smt::RepeatOp)',['../smt-backend.html#smtbvrepeat-llzksmtrepeatop',1,'']]],
  ['smt_20bv_20sdiv_20_3a_3allzk_3a_3asmt_3a_3abvsdivop_40',['&lt;span class=&quot;tt&quot;&gt;smt.bv.sdiv&lt;/span&gt; (llzk::smt::BVSDivOp)',['../smt-backend.html#smtbvsdiv-llzksmtbvsdivop',1,'']]],
  ['smt_20bv_20shl_20_3a_3allzk_3a_3asmt_3a_3abvshlop_41',['&lt;span class=&quot;tt&quot;&gt;smt.bv.shl&lt;/span&gt; (llzk::smt::BVShlOp)',['../smt-backend.html#smtbvshl-llzksmtbvshlop',1,'']]],
  ['smt_20bv_20smod_20_3a_3allzk_3a_3asmt_3a_3abvsmodop_42',['&lt;span class=&quot;tt&quot;&gt;smt.bv.smod&lt;/span&gt; (llzk::smt::BVSModOp)',['../smt-backend.html#smtbvsmod-llzksmtbvsmodop',1,'']]],
  ['smt_20bv_20srem_20_3a_3allzk_3a_3asmt_3a_3abvsremop_43',['&lt;span class=&quot;tt&quot;&gt;smt.bv.srem&lt;/span&gt; (llzk::smt::BVSRemOp)',['../smt-backend.html#smtbvsrem-llzksmtbvsremop',1,'']]],
  ['smt_20bv_20udiv_20_3a_3allzk_3a_3asmt_3a_3abvudivop_44',['&lt;span class=&quot;tt&quot;&gt;smt.bv.udiv&lt;/span&gt; (llzk::smt::BVUDivOp)',['../smt-backend.html#smtbvudiv-llzksmtbvudivop',1,'']]],
  ['smt_20bv_20urem_20_3a_3allzk_3a_3asmt_3a_3abvuremop_45',['&lt;span class=&quot;tt&quot;&gt;smt.bv.urem&lt;/span&gt; (llzk::smt::BVURemOp)',['../smt-backend.html#smtbvurem-llzksmtbvuremop',1,'']]],
  ['smt_20bv_20xor_20_3a_3allzk_3a_3asmt_3a_3abvxorop_46',['&lt;span class=&quot;tt&quot;&gt;smt.bv.xor&lt;/span&gt; (llzk::smt::BVXOrOp)',['../smt-backend.html#smtbvxor-llzksmtbvxorop',1,'']]],
  ['smt_20bv2int_20_3a_3allzk_3a_3asmt_3a_3abv2intop_47',['&lt;span class=&quot;tt&quot;&gt;smt.bv2int&lt;/span&gt; (llzk::smt::BV2IntOp)',['../smt-backend.html#smtbv2int-llzksmtbv2intop',1,'']]],
  ['smt_20check_48',['llzk-smt-check',['../tools.html#llzk-smt-check',1,'']]],
  ['smt_20check_20_3a_3allzk_3a_3asmt_3a_3acheckop_49',['&lt;span class=&quot;tt&quot;&gt;smt.check&lt;/span&gt; (llzk::smt::CheckOp)',['../smt-backend.html#smtcheck-llzksmtcheckop',1,'']]],
  ['smt_20constant_20_3a_3allzk_3a_3asmt_3a_3aboolconstantop_50',['&lt;span class=&quot;tt&quot;&gt;smt.constant&lt;/span&gt; (llzk::smt::BoolConstantOp)',['../smt-backend.html#smtconstant-llzksmtboolconstantop',1,'']]],
  ['smt_20declare_5ffun_20_3a_3allzk_3a_3asmt_3a_3adeclarefunop_51',['&lt;span class=&quot;tt&quot;&gt;smt.declare_fun&lt;/span&gt; (llzk::smt::DeclareFunOp)',['../smt-backend.html#smtdeclare_fun-llzksmtdeclarefunop',1,'']]],
  ['smt_20dialect_52',['&apos;smt&apos; Dialect',['../smt-backend.html#smt-dialect',1,'']]],
  ['smt_20distinct_20_3a_3allzk_3a_3asmt_3a_3adistinctop_53',['&lt;span class=&quot;tt&quot;&gt;smt.distinct&lt;/span&gt; (llzk::smt::DistinctOp)',['../smt-backend.html#smtdistinct-llzksmtdistinctop',1,'']]],
  ['smt_20eq_20_3a_3allzk_3a_3asmt_3a_3aeqop_54',['&lt;span class=&quot;tt&quot;&gt;smt.eq&lt;/span&gt; (llzk::smt::EqOp)',['../smt-backend.html#smteq-llzksmteqop',1,'']]],
  ['smt_20exists_20_3a_3allzk_3a_3asmt_3a_3aexistsop_55',['&lt;span class=&quot;tt&quot;&gt;smt.exists&lt;/span&gt; (llzk::smt::ExistsOp)',['../smt-backend.html#smtexists-llzksmtexistsop',1,'']]],
  ['smt_20forall_20_3a_3allzk_3a_3asmt_3a_3aforallop_56',['&lt;span class=&quot;tt&quot;&gt;smt.forall&lt;/span&gt; (llzk::smt::ForallOp)',['../smt-backend.html#smtforall-llzksmtforallop',1,'']]],
  ['smt_20implies_20_3a_3allzk_3a_3asmt_3a_3aimpliesop_57',['&lt;span class=&quot;tt&quot;&gt;smt.implies&lt;/span&gt; (llzk::smt::ImpliesOp)',['../smt-backend.html#smtimplies-llzksmtimpliesop',1,'']]],
  ['smt_20int_20abs_20_3a_3allzk_3a_3asmt_3a_3aintabsop_58',['&lt;span class=&quot;tt&quot;&gt;smt.int.abs&lt;/span&gt; (llzk::smt::IntAbsOp)',['../smt-backend.html#smtintabs-llzksmtintabsop',1,'']]],
  ['smt_20int_20add_20_3a_3allzk_3a_3asmt_3a_3aintaddop_59',['&lt;span class=&quot;tt&quot;&gt;smt.int.add&lt;/span&gt; (llzk::smt::IntAddOp)',['../smt-backend.html#smtintadd-llzksmtintaddop',1,'']]],
  ['smt_20int_20cmp_20_3a_3allzk_3a_3asmt_3a_3aintcmpop_60',['&lt;span class=&quot;tt&quot;&gt;smt.int.cmp&lt;/span&gt; (llzk::smt::IntCmpOp)',['../smt-backend.html#smtintcmp-llzksmtintcmpop',1,'']]],
  ['smt_20int_20constant_20_3a_3allzk_3a_3asmt_3a_3aintconstantop_61',['&lt;span class=&quot;tt&quot;&gt;smt.int.constant&lt;/span&gt; (llzk::smt::IntConstantOp)',['../smt-backend.html#smtintconstant-llzksmtintconstantop',1,'']]],
  ['smt_20int_20div_20_3a_3allzk_3a_3asmt_3a_3aintdivop_62',['&lt;span class=&quot;tt&quot;&gt;smt.int.div&lt;/span&gt; (llzk::smt::IntDivOp)',['../smt-backend.html#smtintdiv-llzksmtintdivop',1,'']]],
  ['smt_20int_20mod_20_3a_3allzk_3a_3asmt_3a_3aintmodop_63',['&lt;span class=&quot;tt&quot;&gt;smt.int.mod&lt;/span&gt; (llzk::smt::IntModOp)',['../smt-backend.html#smtintmod-llzksmtintmodop',1,'']]],
  ['smt_20int_20mul_20_3a_3allzk_3a_3asmt_3a_3aintmulop_64',['&lt;span class=&quot;tt&quot;&gt;smt.int.mul&lt;/span&gt; (llzk::smt::IntMulOp)',['../smt-backend.html#smtintmul-llzksmtintmulop',1,'']]],
  ['smt_20int_20neg_20_3a_3allzk_3a_3asmt_3a_3aintnegop_65',['&lt;span class=&quot;tt&quot;&gt;smt.int.neg&lt;/span&gt; (llzk::smt::IntNegOp)',['../smt-backend.html#smtintneg-llzksmtintnegop',1,'']]],
  ['smt_20int_20sub_20_3a_3allzk_3a_3asmt_3a_3aintsubop_66',['&lt;span class=&quot;tt&quot;&gt;smt.int.sub&lt;/span&gt; (llzk::smt::IntSubOp)',['../smt-backend.html#smtintsub-llzksmtintsubop',1,'']]],
  ['smt_20int2bv_20_3a_3allzk_3a_3asmt_3a_3aint2bvop_67',['&lt;span class=&quot;tt&quot;&gt;smt.int2bv&lt;/span&gt; (llzk::smt::Int2BVOp)',['../smt-backend.html#smtint2bv-llzksmtint2bvop',1,'']]],
  ['smt_20ite_20_3a_3allzk_3a_3asmt_3a_3aiteop_68',['&lt;span class=&quot;tt&quot;&gt;smt.ite&lt;/span&gt; (llzk::smt::IteOp)',['../smt-backend.html#smtite-llzksmtiteop',1,'']]],
  ['smt_20not_20_3a_3allzk_3a_3asmt_3a_3anotop_69',['&lt;span class=&quot;tt&quot;&gt;smt.not&lt;/span&gt; (llzk::smt::NotOp)',['../smt-backend.html#smtnot-llzksmtnotop',1,'']]],
  ['smt_20or_20_3a_3allzk_3a_3asmt_3a_3aorop_70',['&lt;span class=&quot;tt&quot;&gt;smt.or&lt;/span&gt; (llzk::smt::OrOp)',['../smt-backend.html#smtor-llzksmtorop',1,'']]],
  ['smt_20pop_20_3a_3allzk_3a_3asmt_3a_3apopop_71',['&lt;span class=&quot;tt&quot;&gt;smt.pop&lt;/span&gt; (llzk::smt::PopOp)',['../smt-backend.html#smtpop-llzksmtpopop',1,'']]],
  ['smt_20push_20_3a_3allzk_3a_3asmt_3a_3apushop_72',['&lt;span class=&quot;tt&quot;&gt;smt.push&lt;/span&gt; (llzk::smt::PushOp)',['../smt-backend.html#smtpush-llzksmtpushop',1,'']]],
  ['smt_20reset_20_3a_3allzk_3a_3asmt_3a_3aresetop_73',['&lt;span class=&quot;tt&quot;&gt;smt.reset&lt;/span&gt; (llzk::smt::ResetOp)',['../smt-backend.html#smtreset-llzksmtresetop',1,'']]],
  ['smt_20set_5finfo_20_3a_3allzk_3a_3asmt_3a_3asetinfoop_74',['&lt;span class=&quot;tt&quot;&gt;smt.set_info&lt;/span&gt; (llzk::smt::SetInfoOp)',['../smt-backend.html#smtset_info-llzksmtsetinfoop',1,'']]],
  ['smt_20set_5flogic_20_3a_3allzk_3a_3asmt_3a_3asetlogicop_75',['&lt;span class=&quot;tt&quot;&gt;smt.set_logic&lt;/span&gt; (llzk::smt::SetLogicOp)',['../smt-backend.html#smtset_logic-llzksmtsetlogicop',1,'']]],
  ['smt_20solver_20_3a_3allzk_3a_3asmt_3a_3asolverop_76',['&lt;span class=&quot;tt&quot;&gt;smt.solver&lt;/span&gt; (llzk::smt::SolverOp)',['../smt-backend.html#smtsolver-llzksmtsolverop',1,'']]],
  ['smt_20xor_20_3a_3allzk_3a_3asmt_3a_3axorop_77',['&lt;span class=&quot;tt&quot;&gt;smt.xor&lt;/span&gt; (llzk::smt::XOrOp)',['../smt-backend.html#smtxor-llzksmtxorop',1,'']]],
  ['smt_20yield_20_3a_3allzk_3a_3asmt_3a_3ayieldop_78',['&lt;span class=&quot;tt&quot;&gt;smt.yield&lt;/span&gt; (llzk::smt::YieldOp)',['../smt-backend.html#smtyield-llzksmtyieldop',1,'']]],
  ['smtfunctype_79',['SMTFuncType',['../smt-backend.html#smtfunctype',1,'']]],
  ['solve_20an_20issue_80',['Solve an issue',['../contribution-guide.html#solve-an-issue',1,'']]],
  ['solver_20_3a_3allzk_3a_3asmt_3a_3asolverop_81',['&lt;span class=&quot;tt&quot;&gt;smt.solver&lt;/span&gt; (llzk::smt::SolverOp)',['../smt-backend.html#smtsolver-llzksmtsolverop',1,'']]],
  ['sorttype_82',['SortType',['../smt-backend.html#sorttype',1,'']]],
  ['specialize_20wildcard_20arrays_83',['&lt;span class=&quot;tt&quot;&gt;-llzk-specialize-wildcard-arrays&lt;/span&gt;',['../tools.html#autotoc_md-llzk-specialize-wildcard-arrays',1,'']]],
  ['specific_20options_84',['Specific Options',['../tools.html#llzk-specific-options',1,'LLZK-Specific Options'],['../tools.html#llzk-specific-options-1',1,'LLZK-Specific Options'],['../tools.html#llzk-specific-options-2',1,'LLZK-Specific Options'],['../tools.html#llzk-specific-options-3',1,'LLZK-Specific Options']]],
  ['specification_85',['LLZK Language Specification',['../syntax.html',1,'']]],
  ['srem_20_3a_3allzk_3a_3asmt_3a_3abvsremop_86',['&lt;span class=&quot;tt&quot;&gt;smt.bv.srem&lt;/span&gt; (llzk::smt::BVSRemOp)',['../smt-backend.html#smtbvsrem-llzksmtbvsremop',1,'']]],
  ['standards_87',['Our Standards',['../code-of-conduct.html#our-standards',1,'']]],
  ['started_88',['Getting started',['../contribution-guide.html#getting-started',1,'']]],
  ['store_20_3a_3allzk_3a_3asmt_3a_3aarraystoreop_89',['&lt;span class=&quot;tt&quot;&gt;smt.array.store&lt;/span&gt; (llzk::smt::ArrayStoreOp)',['../smt-backend.html#smtarraystore-llzksmtarraystoreop',1,'']]],
  ['string_20dialect_90',['&apos;string&apos; Dialect',['../dialects.html#string-dialect',1,'']]],
  ['string_20new_20_3a_3allzk_3a_3astring_3a_3alitstringop_91',['&lt;span class=&quot;tt&quot;&gt;string.new&lt;/span&gt; (llzk::string::LitStringOp)',['../dialects.html#stringnew-llzkstringlitstringop',1,'']]],
  ['stringtype_92',['StringType',['../dialects.html#stringtype',1,'']]],
  ['struct_20def_20_3a_3allzk_3a_3acomponent_3a_3astructdefop_93',['&lt;span class=&quot;tt&quot;&gt;struct.def&lt;/span&gt; (llzk::component::StructDefOp)',['../dialects.html#structdef-llzkcomponentstructdefop',1,'']]],
  ['struct_20dialect_94',['&apos;struct&apos; Dialect',['../dialects.html#struct-dialect',1,'']]],
  ['struct_20inlining_95',['&lt;span class=&quot;tt&quot;&gt;-llzk-full-struct-inlining&lt;/span&gt;',['../tools.html#autotoc_md-llzk-full-struct-inlining',1,'']]],
  ['struct_20member_20_3a_3allzk_3a_3acomponent_3a_3amemberdefop_96',['&lt;span class=&quot;tt&quot;&gt;struct.member&lt;/span&gt; (llzk::component::MemberDefOp)',['../dialects.html#structmember-llzkcomponentmemberdefop',1,'']]],
  ['struct_20new_20_3a_3allzk_3a_3acomponent_3a_3acreatestructop_97',['&lt;span class=&quot;tt&quot;&gt;struct.new&lt;/span&gt; (llzk::component::CreateStructOp)',['../dialects.html#structnew-llzkcomponentcreatestructop',1,'']]],
  ['struct_20readm_20_3a_3allzk_3a_3acomponent_3a_3amemberreadop_98',['&lt;span class=&quot;tt&quot;&gt;struct.readm&lt;/span&gt; (llzk::component::MemberReadOp)',['../dialects.html#structreadm-llzkcomponentmemberreadop',1,'']]],
  ['struct_20writem_20_3a_3allzk_3a_3acomponent_3a_3amemberwriteop_99',['&lt;span class=&quot;tt&quot;&gt;struct.writem&lt;/span&gt; (llzk::component::MemberWriteOp)',['../dialects.html#structwritem-llzkcomponentmemberwriteop',1,'']]],
  ['structs_100',['&lt;span class=&quot;tt&quot;&gt;-llzk-inline-structs&lt;/span&gt;',['../tools.html#autotoc_md-llzk-inline-structs',1,'']]],
  ['structtype_101',['StructType',['../dialects.html#structtype',1,'StructType'],['../zklean-backend.html#structtype-1',1,'StructType']]],
  ['structure_20_3a_3allzk_3a_3azkleanlean_3a_3astructdefop_102',['&lt;span class=&quot;tt&quot;&gt;ZKLeanLean.structure&lt;/span&gt; (llzk::zkleanlean::StructDefOp)',['../zklean-backend.html#zkleanleanstructure-llzkzkleanleanstructdefop',1,'']]],
  ['sub_20_3a_3allzk_3a_3afelt_3a_3asubfeltop_103',['&lt;span class=&quot;tt&quot;&gt;felt.sub&lt;/span&gt; (llzk::felt::SubFeltOp)',['../dialects.html#feltsub-llzkfeltsubfeltop',1,'']]],
  ['sub_20_3a_3allzk_3a_3asmt_3a_3aintsubop_104',['&lt;span class=&quot;tt&quot;&gt;smt.int.sub&lt;/span&gt; (llzk::smt::IntSubOp)',['../smt-backend.html#smtintsub-llzksmtintsubop',1,'']]],
  ['sub_20_3a_3allzk_3a_3azkexpr_3a_3asubop_105',['&lt;span class=&quot;tt&quot;&gt;ZKExpr.Sub&lt;/span&gt; (llzk::zkexpr::SubOp)',['../zklean-backend.html#zkexprsub-llzkzkexprsubop',1,'']]],
  ['sub_20_3a_3apcl_3a_3asubop_106',['&lt;span class=&quot;tt&quot;&gt;pcl.sub&lt;/span&gt; (pcl::SubOp)',['../pcl-backend.html#pclsub-pclsubop',1,'']]],
  ['symbol_20def_20tree_107',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-symbol-def-tree&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-symbol-def-tree',1,'']]],
  ['symbol_20use_20graph_108',['&lt;span class=&quot;tt&quot;&gt;-llzk-print-symbol-use-graph&lt;/span&gt;',['../tools.html#autotoc_md-llzk-print-symbol-use-graph',1,'']]],
  ['symbolattr_109',['SymbolAttr',['../smt-backend.html#symbolattr',1,'']]],
  ['syntax_110',['Syntax',['../syntax.html#syntax-1',1,'']]]
];
