#!/usr/bin/env python3
"""Generate FileCheck directives for LLZK lit tests.

This script is a utility to add FileCheck patterns to an MLIR or LLZK file. It was
adapted from the LLVM project's mlir/utils/generate-test-checks.py script.

NOTE: The input .mlir/.llzk is expected to be printed IR, not a stripped-down
variant.

Example usage:
$ scripts/generate-test-checks.py foo.llzk
$ llzk-opt foo.llzk --canonicalize | scripts/generate-test-checks.py
$ llzk-opt foo.llzk --canonicalize | scripts/generate-test-checks.py --source foo.llzk
$ llzk-opt foo.llzk --canonicalize | scripts/generate-test-checks.py --source foo.llzk -i
$ llzk-opt foo.llzk --canonicalize | scripts/generate-test-checks.py --source foo.llzk -i --source_delim_regex='gpu.func @'

In-place updates refuse to modify a dirty Git worktree, including untracked
files, unless --allow-dirty is specified.

In-place updates require --source, cannot be combined with --output, and
replace the source only after generation succeeds. Review generated checks
before using --inplace; they are heuristic and are not authoritative test
specifications.

The script heuristically generates FileCheck directives for the input. By
default it also inserts FileCheck variable substitutions for SSA value names.
If --source is specified, the script inserts generated CHECKs before source
lines matched by --source_delim_regex.
Generated attribute-definition checks stay in the source segment that contains
their definitions, preserving their order when the source is split into
multiple segments.

The script is designed to make adding checks to a test case fast, it is *not*
designed to be authoritative about what constitutes a good test!
"""

# Part of the LLZK Project, under the Apache License v2.0.
# See LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0

import argparse
import os
import re
import stat
import subprocess
import sys
import tempfile

ADVERT_BEGIN = "// NOTE: Assertions have been autogenerated by "
ADVERT_END = """
// The script is designed to make adding checks to
// a test case fast, it is *not* designed to be authoritative
// about what constitutes a good test! The CHECK should be
// minimized and named to reflect the test intent.
"""


# Regex command to match an SSA identifier.
SSA_RE_STR = "[0-9]+|[a-zA-Z$._-][a-zA-Z0-9$._-]*"
SSA_RE = re.compile(SSA_RE_STR)

# Regex matching the left-hand side of an assignment
SSA_RESULTS_STR = r'\s*(%' + SSA_RE_STR + r')(:[0-9]+)*(\s*,\s*(%' + SSA_RE_STR + r'))*\s*='
SSA_RESULTS_RE = re.compile(SSA_RESULTS_STR)

# Regex matching complete attribute-like tokens without consuming inline bodies.
# Only exact tokens registered by an attribute definition are substituted.
ATTR_RE_STR = (
    r'(#[a-zA-Z._-][a-zA-Z0-9._-]*)'
    r'(?![a-zA-Z0-9._$-]|<)'
)
ATTR_RE = re.compile(ATTR_RE_STR)

# Regex matching the left-hand side of an attribute definition
ATTR_DEF_RE_STR = r'\s*' + ATTR_RE_STR + r'\s*='
ATTR_DEF_RE = re.compile(ATTR_DEF_RE_STR)


# Class used to generate and manage string substitution blocks for SSA value
# names.
class VariableNamer:
    def __init__(self, variable_names):
        self.scopes = []
        self.name_counter = 0

        # Number of variable names to still generate in parent scope
        self.generate_in_parent_scope_left = 0

        # Parse variable names
        self.variable_names = [name.upper() for name in variable_names.split(',')]
        self.used_variable_names = set()

    # Generate the following 'n' variable names in the parent scope.
    def generate_in_parent_scope(self, n):
        self.generate_in_parent_scope_left = n

    # Generate a substitution name for the given ssa value name.
    def generate_name(self, source_variable_name):

        # Compute variable name
        variable_name = self.variable_names.pop(0) if len(self.variable_names) > 0 else ''
        if variable_name == '':
            variable_name = "VAL_" + str(self.name_counter)
            self.name_counter += 1

        # Scope where variable name is saved
        scope = len(self.scopes) - 1
        if self.generate_in_parent_scope_left > 0:
            self.generate_in_parent_scope_left -= 1
            scope = len(self.scopes) - 2
        assert(scope >= 0)

        # Save variable
        if variable_name in self.used_variable_names:
            raise RuntimeError(variable_name + ': duplicate variable name')
        self.scopes[scope][source_variable_name] = variable_name
        self.used_variable_names.add(variable_name)

        return variable_name

    # Push a new variable name scope.
    def push_name_scope(self):
        self.scopes.append({})

    # Pop the last variable name scope.
    def pop_name_scope(self):
        self.scopes.pop()

    # Return the level of nesting (number of pushed scopes).
    def num_scopes(self):
        return len(self.scopes)

    # Reset the counter and used variable names.
    def clear_names(self):
        self.name_counter = 0
        self.used_variable_names = set()

class AttributeNamer:

    def __init__(self, attribute_names):
        self.name_counter = 0
        self.attribute_names = [name.upper() for name in attribute_names.split(',')]
        self.map = {}
        self.used_attribute_names = set()

    # Generate a substitution name for the given attribute name.
    def generate_name(self, source_attribute_name):

        # Compute FileCheck name
        attribute_name = self.attribute_names.pop(0) if len(self.attribute_names) > 0 else ''
        if attribute_name == '':
            attribute_name = "ATTR_" + str(self.name_counter)
            self.name_counter += 1

        # Prepend global symbol
        attribute_name = '$' + attribute_name

        # Save attribute
        if attribute_name in self.used_attribute_names:
            raise RuntimeError(attribute_name + ': duplicate attribute name')
        self.map[source_attribute_name] = attribute_name
        self.used_attribute_names.add(attribute_name)
        return attribute_name

    # Get the saved substitution name for the given attribute name, if any.
    def get_name(self, source_attribute_name):
        return self.map.get(source_attribute_name)

# Return the number of SSA results in a line of type
#   %0, %1, ... = ...
# The function returns 0 if there are no results.
def get_num_ssa_results(input_line):
    m = SSA_RESULTS_RE.match(input_line)
    return m.group().count('%') if m else 0


# Process a line of input that has been split at each SSA identifier '%'.
def process_line(line_chunks, variable_namer):
    output_line = ""

    # Process the rest that contained an SSA value name.
    for chunk in line_chunks:
        m = SSA_RE.match(chunk)
        ssa_name = m.group(0) if m is not None else ''

        # Check if an existing variable exists for this name.
        variable = None
        for scope in variable_namer.scopes:
            variable = scope.get(ssa_name)
            if variable is not None:
                break

        # If one exists, then output the existing name.
        if variable is not None:
            output_line += "%[[" + variable + "]]"
        else:
            # Otherwise, generate a new variable.
            variable = variable_namer.generate_name(ssa_name)
            output_line += "%[[" + variable + ":[0-9a-zA-Z_\\.]+]]"

        # Append the non named group.
        output_line += chunk[len(ssa_name) :]

    return output_line.rstrip() + "\n"


def process_source_lines(source_lines, note, args):
    """Return source segments after removing prior generated notes and check directives.

    Source text and comments are preserved unless they match the generator note or a FileCheck
    directive for the selected check prefix. Each source line matching the configured delimiter
    begins a new segment.
    """
    source_split_re = re.compile(args.source_delim_regex)
    directive_suffix = (
        r"(?:-(?:NEXT|SAME|NOT|DAG|LABEL|EMPTY)|-COUNT-(?P<count>[0-9]+))?"
    )
    literal_modifier = r"(?:\{\s*LITERAL\s*(?:,\s*LITERAL\s*)*\})?"
    check_line_re = re.compile(
        r"^\s*//\s*"
        + re.escape(args.check_prefix)
        + directive_suffix
        + literal_modifier
        + r":"
    )
    note_lines = note.splitlines()
    note_variants = [note_lines, [note_lines[0]]]

    def line_without_ending(line):
        """Return a line's text without changing any other source whitespace."""
        return line.rstrip("\r\n")

    source_segments = [[]]
    line_index = 0
    while line_index < len(source_lines):
        # Remove a current or legacy generated note and its separating blank line.
        matched_note_length = next(
            (
                len(candidate)
                for candidate in note_variants
                if [
                    line_without_ending(line)
                    for line in source_lines[
                        line_index : line_index + len(candidate)
                    ]
                ]
                == candidate
            ),
            0,
        )
        if matched_note_length:
            line_index += matched_note_length
            if (
                line_index < len(source_lines)
                and line_without_ending(source_lines[line_index]) == ""
            ):
                line_index += 1
            continue

        line = source_lines[line_index]
        line_text = line_without_ending(line)
        # Remove previous FileCheck directives, but preserve source text that
        # merely contains the check prefix.
        directive_match = check_line_re.match(line_text)
        count = directive_match.group("count") if directive_match else None
        normalized_count = count.lstrip("0") if count is not None else None
        # FileCheck accepts positive decimal counts up to signed 32-bit maximum.
        count_is_valid = count is None or (
            bool(normalized_count)
            and (
                len(normalized_count) < 10
                or (len(normalized_count) == 10 and normalized_count <= "2147483647")
            )
        )
        if directive_match and count_is_valid:
            line_index += 1
            continue
        # Segment the file based on --source_delim_regex.
        if source_split_re.search(line_text):
            source_segments.append([])

        source_segments[-1].append(line)
        line_index += 1
    return source_segments


def _git_environment_without_local_vars():
    """Return a copy of the environment without Git's local variables."""
    result = subprocess.run(
        ["git", "rev-parse", "--local-env-vars"],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            result.stderr.strip() or "git rev-parse --local-env-vars failed"
        )

    # Keep ordinary user configuration while preventing inherited Git state from
    # selecting a different repository or index.
    environment = os.environ.copy()
    for variable in result.stdout.splitlines():
        environment.pop(variable, None)
    return environment


def workspace_is_dirty(path):
    """Return whether Git reports tracked or untracked changes for path's worktree.

    A path with no Git worktree metadata is treated as clean; other Git failures are reported.
    """
    result = subprocess.run(
        [
            "git",
            "-C",
            os.path.dirname(os.path.abspath(path)),
            "status",
            "--porcelain",
            "--untracked-files=all",
        ],
        capture_output=True,
        text=True,
        check=False,
        env=_git_environment_without_local_vars(),
    )
    if result.returncode == 0:
        return bool(result.stdout)
    if not has_git_metadata(path):
        return False
    raise RuntimeError(result.stderr.strip() or "git status failed")


def has_git_metadata(path):
    """Return whether path has a .git entry in it or an ancestor directory."""
    directory = os.path.dirname(os.path.abspath(path))
    while True:
        if os.path.lexists(os.path.join(directory, ".git")):
            return True
        parent = os.path.dirname(directory)
        if parent == directory:
            return False
        directory = parent


def process_attribute_definition(line, attribute_namer, output_segment, check_prefix):
    """Append an attribute-definition check using the selected FileCheck prefix."""
    m = ATTR_DEF_RE.match(line)
    if m:
        attribute_name = attribute_namer.generate_name(m.group(1))
        line = (
            '// ' + check_prefix + ': #[[' + attribute_name
            + ':[0-9a-zA-Z_\\.]+]] =' + line[len(m.group(0)):] + '\n'
        )
        output_segment.append(line)
    return bool(m)

def process_attribute_references(line, attribute_namer):

    output_line = ''
    components = ATTR_RE.split(line)
    for component in components:
        m = ATTR_RE.match(component)
        if m:
            # Preserve inline and unknown tokens; substitute only registered aliases.
            attribute_name = attribute_namer.get_name(m.group(1))
            if attribute_name is None:
                output_line += m.group(1)
            else:
                output_line += '#[[' + attribute_name + ']]'
            output_line += component[len(m.group()):]
        else:
            output_line += component
    return output_line

# Pre-process a line of input to remove any character sequences that will be
# problematic with FileCheck.
def preprocess_line(line):
    # Replace any double brackets, '[[' with escaped replacements. '[['
    # corresponds to variable names in FileCheck.
    output_line = line.replace("[[", "{{\\[\\[}}")

    # Replace any single brackets that are followed by an SSA identifier, the
    # identifier will be replace by a variable; Creating the same situation as
    # above.
    output_line = output_line.replace("[%", "{{\\[}}%")

    return output_line


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument(
        "--check-prefix",
        default="CHECK",
        help="Prefix for generated and replaced FileCheck directives.",
    )
    parser.add_argument(
        "-o",
        "--output",
        nargs="?",
        const="-",
        type=str,
        metavar="FILE",
        help="Write generated output to FILE, or to stdout when FILE is omitted or '-'.",
    )
    parser.add_argument(
        "input", nargs="?", type=argparse.FileType("r"), default=sys.stdin
    )
    parser.add_argument(
        "--source",
        type=str,
        help="Place each generated check block before the corresponding source "
        "segment in this source file. Segments are selected by --source_delim_regex.",
    )
    parser.add_argument(
        "--source_delim_regex",
        type=str,
        default="func @",
        help="Regex searched within each source line; each matching line begins a new segment. "
        "Use '^' when the match must start the line (default: 'func @').",
    )
    parser.add_argument(
        "--starts_from_scope",
        type=int,
        default=0,
        help="Omit the top specified level of content. Includes all levels by default."
    )
    parser.add_argument(
        "-i",
        "--inplace",
        action="store_true",
        default=False,
        help="Update --source in place after successful generation.",
    )
    parser.add_argument(
        "--allow-dirty",
        action="store_true",
        default=False,
        help="Allow in-place updates despite a dirty Git worktree.",
    )
    parser.add_argument(
        "--variable_names",
        type=str,
        default='',
        help="Names to be used in FileCheck regular expression to represent SSA "
        "variables in the order they are encountered. Separate names with commas, "
        "and leave empty entries for default names (e.g.: 'DIM,,SUM,RESULT')")
    parser.add_argument(
        "--attribute_names",
        type=str,
        default='',
        help="Names to be used in FileCheck regular expression to represent "
        "attributes in the order they are defined. Separate names with commas,"
        "commas, and leave empty entries for default names (e.g.: 'MAP0,,,MAP1')")

    args = parser.parse_args()

    def close_input():
        """Close a file opened by argparse without closing process standard input."""
        if args.input is not sys.stdin and not args.input.closed:
            args.input.close()

    if args.inplace and args.output is not None:
        close_input()
        parser.error("--inplace cannot be used with --output")

    if args.inplace:
        if args.source is None:
            close_input()
            parser.error("--inplace requires --source")
        source_argument_path = os.path.abspath(args.source)
        source_path = os.path.realpath(source_argument_path)
        if not os.path.exists(source_path):
            close_input()
            print(f"error: source file does not exist: {args.source}", file=sys.stderr)
            return 1
        if not os.path.isfile(source_path):
            close_input()
            print(f"error: source path is not a regular file: {args.source}", file=sys.stderr)
            return 1
        if not args.allow_dirty:
            try:
                dirty = workspace_is_dirty(source_argument_path) or (
                    source_path != source_argument_path
                    and workspace_is_dirty(source_path)
                )
            except (OSError, RuntimeError) as error:
                close_input()
                print(f"error: unable to check Git worktree status: {error}", file=sys.stderr)
                return 1
            if dirty:
                close_input()
                print(
                    "warning: refusing to modify a dirty Git worktree; "
                    "rerun with --allow-dirty to bypass",
                    file=sys.stderr,
                )
                return 1
    # Open the given input file.
    input_lines = [l.rstrip() for l in args.input]
    close_input()

    # Generate a note used for the generated check file.
    script_name = os.path.basename(__file__)
    autogenerated_note = ADVERT_BEGIN + "scripts/" + script_name + "\n" + ADVERT_END

    source_segments = None
    if args.source:
        with open(
            args.source,
            "r",
            encoding="utf-8",
            errors="surrogateescape",
            newline="",
        ) as source:
            source_segments = process_source_lines(
                source.readlines(), autogenerated_note, args
            )

    temporary_output_path = None
    output = None
    cleanup_errors = []
    try:
        if args.inplace:
            output = tempfile.NamedTemporaryFile(
                mode="w",
                dir=os.path.dirname(source_path),
                prefix="." + os.path.basename(source_path) + ".",
                suffix=".tmp",
                delete=False,
                encoding="utf-8",
                errors="surrogateescape",
                newline="",
            )
            temporary_output_path = output.name
        elif args.output is None or args.output == "-":
            output = sys.stdout
        else:
            try:
                output = open(args.output, "w")
            except OSError as error:
                close_input()
                parser.error(f"argument -o/--output: can't open {args.output!r}: {error}")

        output_segments = [[]]

        # Namers
        variable_namer = VariableNamer(args.variable_names)
        attribute_namer = AttributeNamer(args.attribute_names)

        # Process lines
        for input_line in input_lines:
            if not input_line:
                continue

            # Check if this is an attribute definition and process it
            if process_attribute_definition(
                input_line, attribute_namer, output_segments[-1], args.check_prefix
            ):
                continue

            # Lines with blocks begin with a ^. These lines have a trailing comment
            # that needs to be stripped.
            lstripped_input_line = input_line.lstrip()
            is_block = lstripped_input_line[0] == "^"
            if is_block:
                input_line = input_line.rsplit("//", 1)[0].rstrip()

            cur_level = variable_namer.num_scopes()

            # If the line starts with a '}', pop the last name scope.
            if lstripped_input_line[0] == "}":
                variable_namer.pop_name_scope()
                cur_level = variable_namer.num_scopes()

            # If the line ends with a '{', push a new name scope.
            if input_line[-1] == "{":
                variable_namer.push_name_scope()
                if cur_level == args.starts_from_scope:
                    output_segments.append([])

                # Result SSA values must still be pushed to parent scope
                num_ssa_results = get_num_ssa_results(input_line)
                variable_namer.generate_in_parent_scope(num_ssa_results)

            # Omit lines at the near top level e.g. "module {".
            if cur_level < args.starts_from_scope:
                continue

            if len(output_segments[-1]) == 0:
                variable_namer.clear_names()

            # Preprocess the input to remove any sequences that may be problematic with
            # FileCheck.
            input_line = preprocess_line(input_line)

            # Process uses of attributes in this line
            input_line = process_attribute_references(input_line, attribute_namer)

            # Split the line at the each SSA value name.
            ssa_split = input_line.split("%")

            # If this is a top-level operation use 'CHECK-LABEL', otherwise 'CHECK-NEXT:'.
            if len(output_segments[-1]) != 0 or not ssa_split[0]:
                output_line = "// " + args.check_prefix + "-NEXT:  "

                # Output the first line chunk that does not contain an SSA name.
                output_line += ssa_split[0]

                # Process the rest of the input line.
                output_line += process_line(ssa_split[1:], variable_namer)

            else:
                # Output the first line chunk that does not contain an SSA name for the
                # label.
                output_line = "// " + args.check_prefix + "-LABEL: " + ssa_split[0] + "\n"

                # Process the rest of the input line on separate check lines.
                for argument in ssa_split[1:]:
                    output_line += "// " + args.check_prefix + "-SAME:  "

                    # Pad to align with the original position in the line.
                    output_line += " " * len(ssa_split[0])

                    # Process the rest of the line.
                    output_line += process_line([argument], variable_namer)

            # Append the output line.
            output_segments[-1].append(output_line)

        # Write the output.
        if source_segments:
            if len(output_segments) != len(source_segments):
                print(
                    "error: generated "
                    f"{len(output_segments)} check block(s) for "
                    f"{len(source_segments)} source segment(s); "
                    "review --source_delim_regex",
                    file=sys.stderr,
                )
                return 1
            output.write(autogenerated_note + "\n")
            for check_segment, source_segment in zip(output_segments, source_segments):
                for line in check_segment:
                    output.write(line)
                for line in source_segment:
                    output.write(line)
        else:
            output.write(autogenerated_note + "\n")
            for segment in output_segments:
                if segment:
                    output.write("\n")
                    for output_line in segment:
                        output.write(output_line)
            output.write("\n")

        if args.inplace:
            output.flush()
            output.close()
            # Preserve the source's permission bits across the inode replacement.
            os.chmod(
                temporary_output_path, stat.S_IMODE(os.stat(source_path).st_mode)
            )
            os.replace(temporary_output_path, source_path)
            temporary_output_path = None
        else:
            output.close()
    except OSError as error:
        if args.inplace:
            print(f"error: unable to complete in-place update: {error}", file=sys.stderr)
            return 1
        raise
    finally:
        if args.inplace:
            if output is not None and not output.closed:
                try:
                    output.close()
                except OSError as error:
                    cleanup_errors.append(("close temporary output", error))
            if temporary_output_path is not None:
                try:
                    os.unlink(temporary_output_path)
                except FileNotFoundError:
                    pass
                except OSError as error:
                    cleanup_errors.append(("remove temporary output file", error))

            for action, error in cleanup_errors:
                print(f"error: unable to {action}: {error}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())


import contextlib
import io
import pathlib
import unittest
import warnings
from unittest import mock


class _UnclosableStringIO(io.StringIO):
    """Capture output without allowing main() to close the test buffer."""

    def close(self):
        """Keep the captured text available after the utility closes stdout."""
        self.flush()


class GenerateTestChecksTests(unittest.TestCase):
    """Exercise output, source preservation, Git worktree safety, and failures."""

    MINIMAL_MODULE = "module {\n  func.func @main() {\n  }\n}\n"

    def setUp(self):
        """Give each test an isolated filesystem and clean it up afterward."""
        self.temporary_directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary_directory.cleanup)
        self.root = pathlib.Path(self.temporary_directory.name)

    def write_file(self, name, contents):
        """Create a UTF-8 test file below the per-test temporary directory."""
        path = self.root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents, encoding="utf-8")
        return path

    def write_bytes(self, name, contents):
        """Create a byte-for-byte test file below the per-test temporary directory."""
        path = self.root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(contents)
        return path

    def invoke(self, *arguments):
        """Invoke main with real command-line parsing and captured output."""
        original_argv = sys.argv
        stdout = _UnclosableStringIO()
        stderr = _UnclosableStringIO()
        try:
            sys.argv = [__file__, *arguments]
            with warnings.catch_warnings():
                warnings.simplefilter("ignore", PendingDeprecationWarning)
                with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
                    try:
                        exit_code = main()
                    except SystemExit as error:
                        exit_code = error.code
        finally:
            sys.argv = original_argv
        return exit_code, stdout.getvalue(), stderr.getvalue()

    def assert_no_temporary_output(self, source):
        """Ensure a failed in-place update did not leave a replacement file behind."""
        self.assertEqual(list(source.parent.glob(f".{source.name}.*.tmp")), [])

    def run_git(self, repository, *arguments):
        """Run Git in an isolated test repository."""
        environment = _git_environment_without_local_vars()
        environment["GIT_CONFIG_GLOBAL"] = os.devnull
        environment["GIT_CONFIG_NOSYSTEM"] = "1"
        return subprocess.run(
            ["git", "-C", str(repository), *arguments],
            capture_output=True,
            text=True,
            check=True,
            env=environment,
        )

    def test_stdout_and_named_output_match(self):
        """Default, `--output` without a path, and named output generate the same checks."""
        input_path = self.write_file(
            "input.llzk",
            self.MINIMAL_MODULE,
        )
        named_output = self.root / "named-output.llzk"

        stdout_code, stdout_output, stdout_error = self.invoke(str(input_path))
        implicit_code, implicit_output, implicit_error = self.invoke(
            str(input_path), "--output"
        )
        named_code, _, named_error = self.invoke(
            "-o", str(named_output), str(input_path)
        )

        self.assertEqual(stdout_code, 0)
        self.assertEqual(implicit_code, 0)
        self.assertEqual(named_code, 0)
        self.assertEqual(stdout_error, "")
        self.assertEqual(implicit_error, "")
        self.assertEqual(named_error, "")
        self.assertEqual(implicit_output, stdout_output)
        self.assertEqual(named_output.read_text(encoding="utf-8"), stdout_output)
        self.assertIn("NOTE: Assertions have been autogenerated", stdout_output)
        self.assertIn("// CHECK-LABEL:", stdout_output)

    def test_output_without_path_conflicts_with_inplace(self):
        """`--output` without a path cannot silently become an in-place update."""
        source = self.write_file("source.llzk", "module {\n}\n")
        input_path = self.write_file("input.llzk", "module {\n}\n")
        before = source.read_bytes()

        exit_code, _, error = self.invoke(
            "--source",
            str(source),
            "--inplace",
            "--allow-dirty",
            str(input_path),
            "--output",
        )

        self.assertEqual(exit_code, 2)
        self.assertIn("--inplace cannot be used with --output", error)
        self.assertEqual(source.read_bytes(), before)

    def test_named_output_reports_missing_parent(self):
        """Named output reports an invalid parent without creating partial output."""
        input_path = self.write_file(
            "input.llzk",
            self.MINIMAL_MODULE,
        )
        named_output = self.root / "missing" / "named-output.llzk"

        exit_code, _, error = self.invoke("--output", str(named_output), str(input_path))

        self.assertEqual(exit_code, 2)
        self.assertIn("argument -o/--output: can't open", error)
        self.assertFalse(named_output.exists())

    def test_inplace_preserves_source_bytes_across_repeated_runs(self):
        """In-place regeneration preserves non-generated bytes and line endings."""
        source = self.write_bytes(
            "source.llzk",
            b"// NOTE: Assertions have been autogenerated by scripts/generate-test-checks.py\r\n"
            b"\r\n"
            b"// CHECK-LABEL: stale\r\n"
            b"#map = affine_map<(d0) -> (d0)>  \r\n"
            b"\t\r\n"
            b"module {  \r\n"
            b"  // source comment with trailing spaces   \r\n"
            b"  func.func @main() {\r\n"
            b"  }  \r\n"
            b"}\r\n",
        )
        input_path = self.write_file(
            "input.llzk",
            "#map = affine_map<(d0) -> (d0)>\n"
            "module {\n"
            "  func.func @main() {\n"
            "  }\n"
            "}\n",
        )
        before = source.read_bytes()

        first_code, _, first_error = self.invoke(
            "--source",
            str(source),
            "--source_delim_regex=^module ",
            "--allow-dirty",
            "-i",
            str(input_path),
        )
        first_contents = source.read_bytes()
        second_code, _, second_error = self.invoke(
            "--source",
            str(source),
            "--source_delim_regex=^module ",
            "--allow-dirty",
            "-i",
            str(input_path),
        )

        self.assertEqual(first_code, 0)
        self.assertEqual(second_code, 0)
        self.assertEqual(first_error, "")
        self.assertEqual(second_error, "")
        self.assertNotEqual(first_contents, before)
        self.assertEqual(first_contents, source.read_bytes())
        self.assertEqual(
            first_contents,
            b"// NOTE: Assertions have been autogenerated by "
            b"scripts/generate-test-checks.py\n"
            b"\n"
            b"// The script is designed to make adding checks to\n"
            b"// a test case fast, it is *not* designed to be authoritative\n"
            b"// about what constitutes a good test! The CHECK should be\n"
            b"// minimized and named to reflect the test intent.\n"
            b"\n"
            b"// CHECK: #[[$ATTR_0:[0-9a-zA-Z_\\.]+]] = "
            b"affine_map<(d0) -> (d0)>\n"
            b"#map = affine_map<(d0) -> (d0)>  \r\n"
            b"\t\r\n"
            b"// CHECK-LABEL: module {\n"
            b"// CHECK-NEXT:    func.func @main() {\n"
            b"// CHECK-NEXT:    }\n"
            b"// CHECK-NEXT:  }\n"
            b"module {  \r\n"
            b"  // source comment with trailing spaces   \r\n"
            b"  func.func @main() {\r\n"
            b"  }  \r\n"
            b"}\r\n",
        )

    def test_inplace_preserves_non_directive_comments_and_permissions(self):
        """In-place updates preserve non-directive source text and permission bits."""
        source = self.write_file(
            "source.llzk",
            "#map = affine_map<(d0) -> (d0)>\n"
            "module {\n"
            "  // CHECK-this is an invariant comment\n"
            "  func.func @CHECK() {\n"
            "  }\n"
            "}\n",
        )
        input_path = self.write_file(
            "input.llzk",
            "#map = affine_map<(d0) -> (d0)>\n"
            "module {\n"
            "  func.func @CHECK() {\n"
            "  }\n"
            "}\n",
        )
        source.chmod(0o740)

        first_code, _, first_error = self.invoke(
            "--source",
            str(source),
            "--source_delim_regex=^module ",
            "-i",
            str(input_path),
        )
        first_contents = source.read_text(encoding="utf-8")
        second_code, _, second_error = self.invoke(
            "--source",
            str(source),
            "--source_delim_regex=^module ",
            "-i",
            str(input_path),
        )

        self.assertEqual(first_code, 0)
        self.assertEqual(second_code, 0)
        self.assertEqual(first_error, "")
        self.assertEqual(second_error, "")
        self.assertEqual(first_contents, source.read_text(encoding="utf-8"))
        self.assertIn("func.func @CHECK()", first_contents)
        self.assertIn("// CHECK-this is an invariant comment", first_contents)
        self.assertEqual(
            first_contents.count("NOTE: Assertions have been autogenerated"), 1
        )
        self.assertEqual(stat.S_IMODE(source.stat().st_mode), 0o740)

    def test_custom_prefix_removes_only_selected_directives(self):
        """Regeneration replaces one prefix's directives and preserves other comments."""
        directives = (
            "ALT: stale plain",
            "ALT-NEXT: stale next",
            "ALT-SAME: stale same",
            "ALT-NOT: stale not",
            "ALT-DAG: stale dag",
            "ALT-LABEL: stale label",
            "ALT-EMPTY: stale empty",
            "ALT-COUNT-0002: stale count",
            "ALT-COUNT-2147483647: stale maximum count",
            "ALT-NEXT{LITERAL}: stale literal",
        )
        preserved = (
            "ALT-FOO: preserve unknown suffix",
            "ALT-COUNT-0: preserve invalid count",
            "ALT-COUNT-2147483648: preserve out-of-range count",
            "ALT-explanation: preserve comment",
            "CHECK: preserve another prefix",
        )
        source_text = (
            "#map = affine_map<(d0) -> (d0)>\n"
            "module {\n"
            + "".join(f"  // {line}\n" for line in directives + preserved)
            + "  func.func @main() {\n"
            "  }\n"
            "}\n"
        )
        source = self.write_file("source.llzk", source_text)
        input_path = self.write_file(
            "input.llzk",
            "#map = affine_map<(d0) -> (d0)>\n"
            "module {\n"
            "  func.func @main() {\n"
            "  }\n"
            "}\n",
        )

        first_code, _, first_error = self.invoke(
            "--source",
            str(source),
            "--source_delim_regex=^module ",
            "--check-prefix=ALT",
            "--allow-dirty",
            "-i",
            str(input_path),
        )
        first_contents = source.read_bytes()
        second_code, _, second_error = self.invoke(
            "--source",
            str(source),
            "--source_delim_regex=^module ",
            "--check-prefix=ALT",
            "--allow-dirty",
            "-i",
            str(input_path),
        )
        contents = source.read_text(encoding="utf-8")

        self.assertEqual(first_code, 0)
        self.assertEqual(second_code, 0)
        self.assertEqual(first_error, "")
        self.assertEqual(second_error, "")
        self.assertEqual(source.read_bytes(), first_contents)
        for directive in directives:
            self.assertNotIn(directive, contents)
        for comment in preserved:
            self.assertIn(f"// {comment}", contents)
        self.assertIn("// ALT-LABEL:", contents)
        self.assertIn("// ALT: #[[$ATTR_0:", contents)
        self.assertIn("#map = affine_map<(d0) -> (d0)>", contents)

    def test_conflicting_output_modes_are_rejected(self):
        """In-place and named output modes cannot be combined."""
        source = self.write_file(
            "source.llzk",
            "module {\n  // source must remain unchanged\n}\n",
        )
        input_path = self.write_file(
            "input.llzk",
            "module {\n}\n",
        )
        before = source.read_bytes()
        output_path = self.root / "output.llzk"
        exit_code, _, error = self.invoke(
            "--source",
            str(source),
            "--inplace",
            "--output",
            str(output_path),
            str(input_path),
        )

        self.assertEqual(exit_code, 2)
        self.assertIn("--inplace cannot be used with --output", error)
        self.assertEqual(source.read_bytes(), before)
        self.assertFalse(output_path.exists())

    def test_legacy_one_line_note_is_removed(self):
        """Regeneration removes the one-line note emitted by older script versions."""
        input_path = self.write_file(
            "input.llzk",
            "module {\n  func.func @legacy() {\n  }\n}\n",
        )
        first_line = (
            "// NOTE: Assertions have been autogenerated by "
            "scripts/generate-test-checks.py"
        )
        source = self.write_file(
            "source.llzk",
            "module {\n"
            "  func.func @legacy() {\n"
            "  }\n"
            "}\n"
            + first_line
            + "\n\n// CHECK-LABEL: stale\n",
        )

        exit_code, _, error = self.invoke(
            "--source",
            str(source),
            "--source_delim_regex=^module ",
            "--allow-dirty",
            "-i",
            str(input_path),
        )
        contents = source.read_text(encoding="utf-8")

        self.assertEqual(exit_code, 0)
        self.assertEqual(error, "")
        self.assertEqual(contents.count("NOTE: Assertions have been autogenerated"), 1)
        self.assertNotIn("CHECK-LABEL: stale", contents)
        self.assertIn("The CHECK should be", contents)

    def test_inplace_requires_source(self):
        """In-place mode rejects invocations without a source path."""
        exit_code, _, error = self.invoke("--inplace")

        self.assertEqual(exit_code, 2)
        self.assertIn("--inplace requires --source", error)

    def test_invalid_source_paths_are_rejected_before_output(self):
        """Missing and non-file source paths fail before creating replacement output."""
        input_path = self.write_file("input.llzk", "module {\n}\n")
        missing = self.root / "missing.llzk"
        directory = self.root / "source-directory"
        directory.mkdir()

        for source, expected in (
            (missing, "source file does not exist"),
            (directory, "source path is not a regular file"),
        ):
            with self.subTest(source=source):
                exit_code, _, error = self.invoke(
                    "--source", str(source), "--allow-dirty", "-i", str(input_path)
                )

                self.assertEqual(exit_code, 1)
                self.assertIn(expected, error)
                self.assertEqual(list(self.root.rglob("*.tmp")), [])

    def test_segment_mismatch_preserves_source(self):
        """Mismatched generated and source segments leave the source unchanged."""
        source = self.write_file(
            "source.llzk",
            "module @First {\n}\nmodule @Second {\n}\n",
        )
        input_path = self.write_file(
            "input.llzk",
            "module @First {\n}\n",
        )
        before = source.read_bytes()

        exit_code, _, error = self.invoke(
            "--source",
            str(source),
            "--source_delim_regex=^module ",
            "--allow-dirty",
            "-i",
            str(input_path),
        )

        self.assertEqual(exit_code, 1)
        self.assertIn("check block(s) for", error)
        self.assertEqual(source.read_bytes(), before)
        self.assert_no_temporary_output(source)

    def test_generation_failure_preserves_source_and_cleans_temporary_file(self):
        """A generation exception leaves the original source and no temporary file."""
        source = self.write_file(
            "source.llzk",
            "module {\n"
            "  func.func @main() {\n"
            "    %0 = \"test.op\"() : () -> i32\n"
            "    %1 = \"test.op\"() : () -> i32\n"
            "  }\n"
            "}\n",
        )
        input_path = self.write_file(
            "input.llzk",
            "module {\n"
            "  func.func @main() {\n"
            "    %0 = \"test.op\"() : () -> i32\n"
            "    %1 = \"test.op\"() : () -> i32\n"
            "  }\n"
            "}\n",
        )
        before = source.read_text(encoding="utf-8")

        with self.assertRaisesRegex(RuntimeError, "duplicate variable name"):
            self.invoke(
                "--source",
                str(source),
                "--source_delim_regex=^module ",
                "--variable_names=X,X",
                "--allow-dirty",
                "-i",
                str(input_path),
            )

        self.assertEqual(source.read_text(encoding="utf-8"), before)
        self.assert_no_temporary_output(source)

    def test_replacement_failure_preserves_source_and_cleans_temporary_file(self):
        """A replacement exception leaves the original source and removes the temporary file."""
        source = self.write_file(
            "source.llzk",
            self.MINIMAL_MODULE,
        )
        input_path = self.write_file(
            "input.llzk",
            self.MINIMAL_MODULE,
        )
        before = source.read_text(encoding="utf-8")

        def fail_replace(temporary, _target):
            """Fail after the temporary output exists to exercise cleanup."""
            self.assertTrue(pathlib.Path(temporary).exists())
            raise OSError("injected replace failure")

        with mock.patch.object(os, "replace", side_effect=fail_replace):
            exit_code, _, error = self.invoke(
                "--source",
                str(source),
                "--source_delim_regex=^module ",
                "--allow-dirty",
                "-i",
                str(input_path),
            )

        self.assertEqual(exit_code, 1)
        self.assertIn("unable to complete in-place update: injected replace failure", error)
        self.assertEqual(source.read_text(encoding="utf-8"), before)
        self.assert_no_temporary_output(source)

    def test_cleanup_failure_does_not_mask_replacement_failure(self):
        """A cleanup error is reported while the primary replacement error remains visible."""
        source = self.write_file(
            "source.llzk",
            self.MINIMAL_MODULE,
        )
        input_path = self.write_file(
            "input.llzk",
            self.MINIMAL_MODULE,
        )
        temporary_paths = []
        real_unlink = os.unlink

        def fail_replace(temporary, _target):
            """Fail the primary operation after the temporary output exists."""
            temporary_paths.append(temporary)
            raise OSError("injected replace failure")

        def fail_unlink(_temporary):
            """Fail cleanup so it cannot hide the replacement failure."""
            raise OSError("injected cleanup failure")

        try:
            with mock.patch.object(os, "replace", side_effect=fail_replace), mock.patch.object(
                os, "unlink", side_effect=fail_unlink
            ):
                exit_code, _, error = self.invoke(
                    "--source",
                    str(source),
                    "--source_delim_regex=^module ",
                    "--allow-dirty",
                    "-i",
                    str(input_path),
                )
        finally:
            for temporary in temporary_paths:
                if pathlib.Path(temporary).exists():
                    real_unlink(temporary)

        self.assertEqual(exit_code, 1)
        self.assertIn(
            "error: unable to complete in-place update: injected replace failure", error
        )
        self.assertIn(
            "error: unable to remove temporary output file: injected cleanup failure",
            error,
        )

    def test_dirty_worktree_is_refused_unless_explicitly_allowed(self):
        """The safe default refuses dirty worktrees while --allow-dirty permits updates."""
        source = self.write_file(
            "source.llzk",
            self.MINIMAL_MODULE,
        )
        input_path = self.write_file(
            "input.llzk",
            self.MINIMAL_MODULE,
        )
        before = source.read_text(encoding="utf-8")

        dirty_check = mock.Mock(return_value=True)
        with mock.patch.dict(globals(), {"workspace_is_dirty": dirty_check}):
            exit_code, _, error = self.invoke(
                "--source", str(source), "-i", str(input_path)
            )

        self.assertEqual(exit_code, 1)
        self.assertIn("refusing to modify a dirty Git worktree", error)
        self.assertEqual(source.read_text(encoding="utf-8"), before)
        dirty_check.assert_called_once()

        dirty_check = mock.Mock(return_value=True)
        with mock.patch.dict(globals(), {"workspace_is_dirty": dirty_check}):
            exit_code, _, error = self.invoke(
                "--source",
                str(source),
                "--allow-dirty",
                "-i",
                str(input_path),
            )

        self.assertEqual(exit_code, 0)
        self.assertEqual(error, "")
        dirty_check.assert_not_called()
        self.assertNotEqual(source.read_text(encoding="utf-8"), before)
        self.assertIn(
            "NOTE: Assertions have been autogenerated",
            source.read_text(encoding="utf-8"),
        )

    def test_git_status_errors_are_reported_before_modification(self):
        """A Git-status failure stops an in-place update before creating output."""
        source = self.write_file(
            "source.llzk",
            self.MINIMAL_MODULE,
        )
        input_path = self.write_file(
            "input.llzk",
            self.MINIMAL_MODULE,
        )
        before = source.read_text(encoding="utf-8")

        with mock.patch.dict(
            globals(),
            {
                "workspace_is_dirty": mock.Mock(
                    side_effect=RuntimeError("injected git status failure")
                )
            },
        ):
            exit_code, _, error = self.invoke(
                "--source", str(source), "-i", str(input_path)
            )

        self.assertEqual(exit_code, 1)
        self.assertIn("unable to check Git worktree status", error)
        self.assertEqual(source.read_text(encoding="utf-8"), before)
        self.assert_no_temporary_output(source)

    def test_symlink_checks_both_worktrees_and_preserves_link(self):
        """A symlink update requires clean link and target worktrees and preserves the link."""
        link_repository = self.root / "link-repository"
        target_repository = self.root / "target-repository"
        link_repository.mkdir()
        target_repository.mkdir()

        self.run_git(link_repository, "init", "--quiet")
        self.run_git(target_repository, "init", "--quiet")
        target = self.write_file(
            "target-repository/source.llzk",
            self.MINIMAL_MODULE,
        )
        link = link_repository / "source.llzk"
        link.symlink_to(target)
        input_path = self.write_file(
            "input.llzk",
            self.MINIMAL_MODULE,
        )
        for repository in (link_repository, target_repository):
            self.run_git(repository, "add", ".")
            self.run_git(
                repository,
                "-c",
                "user.name=LLZK Tests",
                "-c",
                "user.email=tests@example.invalid",
                "commit",
                "--quiet",
                "-m",
                "fixture",
            )
        before = target.read_bytes()

        link_dirty = self.write_file("link-repository/.hidden", "untracked\n")
        link_code, _, link_error = self.invoke(
            "--source", str(link), "-i", str(input_path)
        )
        link_dirty.unlink()
        self.assertEqual(link_code, 1)
        self.assertIn("refusing to modify a dirty Git worktree", link_error)
        self.assertEqual(target.read_bytes(), before)

        target_dirty = self.write_file("target-repository/.hidden", "untracked\n")
        target_code, _, target_error = self.invoke(
            "--source", str(link), "-i", str(input_path)
        )
        target_dirty.unlink()
        self.assertEqual(target_code, 1)
        self.assertIn("refusing to modify a dirty Git worktree", target_error)
        self.assertEqual(target.read_bytes(), before)

        exit_code, _, error = self.invoke(
            "--source",
            str(link),
            "--source_delim_regex=^module ",
            "-i",
            str(input_path),
        )

        self.assertEqual(exit_code, 0)
        self.assertEqual(error, "")
        self.assertTrue(link.is_symlink())
        self.assertIn(
            "NOTE: Assertions have been autogenerated", target.read_text(encoding="utf-8")
        )

    def test_inplace_uses_real_git_status_for_tracked_and_untracked_changes(self):
        """Tracked and hidden untracked changes both block an in-place update."""
        repository = self.root / "repository"
        repository.mkdir()

        self.run_git(repository, "init", "--quiet")
        self.run_git(repository, "config", "status.showUntrackedFiles", "no")
        source = self.write_file(
            "repository/source.llzk",
            self.MINIMAL_MODULE,
        )
        input_path = self.write_file(
            "input.llzk",
            self.MINIMAL_MODULE,
        )
        self.run_git(repository, "add", "source.llzk")
        self.run_git(
            repository,
            "-c",
            "user.name=LLZK Tests",
            "-c",
            "user.email=tests@example.invalid",
            "commit",
            "--quiet",
            "-m",
            "fixture",
        )
        hidden = self.write_file("repository/.hidden", "untracked\n")
        before = source.read_bytes()

        untracked_code, _, untracked_error = self.invoke(
            "--source", str(source), "-i", str(input_path)
        )
        untracked_contents = source.read_bytes()
        hidden.unlink()
        source.write_bytes(before + b"// tracked change\n")
        tracked_before = source.read_bytes()
        tracked_code, _, tracked_error = self.invoke(
            "--source", str(source), "-i", str(input_path)
        )
        tracked_contents = source.read_bytes()
        source.write_bytes(before)
        success_code, _, success_error = self.invoke(
            "--source", str(source), "-i", str(input_path)
        )

        self.assertEqual(untracked_code, 1)
        self.assertIn("refusing to modify a dirty Git worktree", untracked_error)
        self.assertEqual(untracked_contents, before)
        self.assertEqual(tracked_code, 1)
        self.assertIn("refusing to modify a dirty Git worktree", tracked_error)
        self.assertEqual(tracked_contents, tracked_before)
        self.assertEqual(success_code, 0)
        self.assertEqual(success_error, "")
        self.assertNotEqual(source.read_bytes(), before)
        self.assertIn(b"NOTE: Assertions have been autogenerated", source.read_bytes())

    def test_inplace_ignores_repository_selection_environment(self):
        """A clean decoy repository cannot hide a dirty source worktree."""
        actual_repository = self.root / "actual-repository"
        decoy_repository = self.root / "decoy-repository"
        actual_repository.mkdir()
        decoy_repository.mkdir()
        self.run_git(actual_repository, "init", "--quiet")
        self.run_git(decoy_repository, "init", "--quiet")

        source = self.write_file(
            "actual-repository/source.llzk", self.MINIMAL_MODULE
        )
        input_path = self.write_file("input.llzk", self.MINIMAL_MODULE)
        self.run_git(actual_repository, "add", "source.llzk")
        self.run_git(
            actual_repository,
            "-c",
            "user.name=LLZK Tests",
            "-c",
            "user.email=tests@example.invalid",
            "commit",
            "--quiet",
            "-m",
            "source fixture",
        )
        source.write_text(
            "module {\n"
            "  // dirty source\n"
            "  func.func @main() {\n"
            "  }\n"
            "}\n",
            encoding="utf-8",
        )
        before = source.read_bytes()

        with mock.patch.dict(
            os.environ,
            {
                "GIT_DIR": str(decoy_repository / ".git"),
                "GIT_WORK_TREE": str(decoy_repository),
            },
        ):
            exit_code, _, error = self.invoke(
                "--source",
                str(source),
                "--source_delim_regex=^module ",
                "-i",
                str(input_path),
            )

        self.assertEqual(exit_code, 1)
        self.assertIn("refusing to modify a dirty Git worktree", error)
        self.assertEqual(source.read_bytes(), before)
        self.assert_no_temporary_output(source)

    def test_run_git_ignores_global_configuration(self):
        """Fixture Git commands do not depend on developer-global signing settings."""
        repository = self.root / "repository"
        repository.mkdir()
        self.run_git(repository, "init", "--quiet")
        self.write_file("repository/source.llzk", self.MINIMAL_MODULE)
        global_config = self.write_file(
            "global.gitconfig",
            "[commit]\n"
            "    gpgSign = true\n"
            "[gpg]\n"
            "    program = /path/that/does/not/exist\n",
        )

        with mock.patch.dict(os.environ, {"GIT_CONFIG_GLOBAL": str(global_config)}):
            self.run_git(repository, "add", ".")
            self.run_git(
                repository,
                "-c",
                "user.name=LLZK Tests",
                "-c",
                "user.email=tests@example.invalid",
                "commit",
                "--quiet",
                "-m",
                "fixture",
            )

        self.assertEqual(
            self.run_git(repository, "status", "--porcelain").stdout,
            "",
        )

    def test_workspace_is_dirty_handles_localized_non_repository_and_status_failure(self):
        """Non-repository paths are clean while other Git failures are reported."""
        non_repository_source = self.write_file(
            "non-repository/source.llzk", "module {}\n"
        )
        repository_source = self.write_file(
            "repository/source.llzk", "module {}\n"
        )
        (repository_source.parent / ".git").mkdir()
        non_repository = subprocess.CompletedProcess(
            args=[],
            returncode=128,
            stdout="",
            stderr="fatal: dépôt Git introuvable",
        )
        status_failure = subprocess.CompletedProcess(
            args=[], returncode=2, stdout="", stderr="fatal: injected status failure"
        )

        with mock.patch.dict(
            globals(),
            {"_git_environment_without_local_vars": mock.Mock(return_value={})},
        ), mock.patch.object(
            subprocess, "run", side_effect=[non_repository, status_failure]
        ):
            self.assertFalse(workspace_is_dirty(non_repository_source))
            with self.assertRaisesRegex(RuntimeError, "injected status failure"):
                workspace_is_dirty(repository_source)

    def test_workspace_is_dirty_rejects_malformed_repository_metadata(self):
        """A broken .git entry is a status failure rather than a clean worktree."""
        source = self.write_file("broken/source.llzk", "module {}\n")
        self.write_file("broken/.git", "gitdir: missing\n")

        with self.assertRaises(RuntimeError):
            workspace_is_dirty(source)
