//===- AttrCAPITestGen.cpp - C API test generator for attributes ----------===//
//
// Part of the LLZK Project, under the Apache License v2.0.
// See LICENSE.txt for license information.
// Copyright 2025 Veridise Inc.
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// AttrCAPITestGen generates unit tests for the C API attributes generated by
// AttrCAPIGen. These are link-time tests that ensure all generated functions
// compile and link properly.
//
// Test Strategy:
// - Each test creates a dummy attribute (IntegerAttr)
// - Tests then call the generated C API functions inside an if statement that
//   checks if the dummy attribute is of the target type (always false)
// - This ensures compile-time type checking and link-time symbol resolution
//   without actually executing the code at runtime
//
//===----------------------------------------------------------------------===//

#include "CommonAttrOrTypeCAPITestGen.h"
#include "CommonCAPIGen.h"

#include <mlir/TableGen/AttrOrTypeDef.h>
#include <mlir/TableGen/Dialect.h>
#include <mlir/TableGen/GenInfo.h>

#include <llvm/ADT/StringExtras.h>
#include <llvm/Support/CommandLine.h>
#include <llvm/Support/FormatVariadic.h>
#include <llvm/TableGen/Record.h>
#include <llvm/TableGen/TableGenBackend.h>

using namespace mlir;
using namespace mlir::tblgen;

/// Emit C API tests for attributes
static bool emitAttrCAPITests(const llvm::RecordKeeper &records, raw_ostream &os) {
  // Generate file header
  emitSourceFileHeader("Attr C API Tests", os, records);

  // Create generator with test object creation expression
  AttrOrTypeTestGenerator generator("Attribute", os);

  // Generate test class prologue
  generator.genTestClassPrologue();

  // Generate tests for each attribute
  for (const auto *def : records.getAllDerivedDefinitions("AttrDef")) {
    const AttrOrTypeDef attr(def);
    generator.genCompleteRecord(attr, false);
  }

  return false;
}

static mlir::GenRegistration genAttrCAPITests(
    "gen-attr-capi-tests", "Generate attribute C API unit tests", &emitAttrCAPITests
);
