//===- TypeCAPITestGen.cpp - C API test generator for types ---------------===//
//
// Part of the LLZK Project, under the Apache License v2.0.
// See LICENSE.txt for license information.
// Copyright 2025 Veridise Inc.
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// TypeCAPITestGen generates unit tests for the C API types generated by
// TypeCAPIGen. These are link-time tests that ensure all generated functions
// compile and link properly.
//
// Test Strategy:
// - Each test creates a dummy type (IndexType)
// - Tests then call the generated C API functions inside an if statement that
//   checks if the dummy type is of the target type (always false)
// - This ensures compile-time type checking and link-time symbol resolution
//   without actually executing the code at runtime
//
//===----------------------------------------------------------------------===//

#include "CommonAttrOrTypeCAPITestGen.h"
#include "CommonCAPIGen.h"

#include <mlir/TableGen/AttrOrTypeDef.h>
#include <mlir/TableGen/Dialect.h>
#include <mlir/TableGen/GenInfo.h>

#include <llvm/ADT/StringExtras.h>
#include <llvm/Support/CommandLine.h>
#include <llvm/Support/FormatVariadic.h>
#include <llvm/TableGen/Record.h>
#include <llvm/TableGen/TableGenBackend.h>

using namespace mlir;
using namespace mlir::tblgen;

/// Emit C API tests for types
static bool emitTypeCAPITests(const llvm::RecordKeeper &records, raw_ostream &os) {
  // Generate file header
  emitSourceFileHeader("Type C API Tests", os, records);

  // Create generator with test object creation expression
  AttrOrTypeTestGenerator generator("Type", os);

  // Generate test class prologue
  generator.genTestClassPrologue();

  // Generate tests for each type
  for (const auto *def : records.getAllDerivedDefinitions("TypeDef")) {
    const AttrOrTypeDef type(def);
    generator.genCompleteRecord(type, true);
  }

  return false;
}

static mlir::GenRegistration
    genTypeCAPITests("gen-type-capi-tests", "Generate type C API unit tests", &emitTypeCAPITests);
