//===-- CAPI.cpp ------------------------------------------------*- C++ -*-===//
//
// Part of the LLZK Project, under the Apache License v2.0.
// See LICENSE.txt for license information.
// Copyright 2026 Project LLZK
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
///
/// \file
/// This file includes the autogenerated CAPI functions to load the passes.
///
//===----------------------------------------------------------------------===//

#include "smt/Conversions/ConversionPasses.h" // IWYU pragma: keep

#include "llzk-c/Target/SMT.h"

#include <mlir/CAPI/Pass.h>

using namespace llzk::smt;

/// Adapt the C API group name to the C++ conversion pass registration function.
static inline void registerSMTConversionPasses() { registerConversionPasses(); }

#include "smt/Conversions/ConversionPasses.capi.cpp.inc"
