name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release:
    if: endsWith(github.head_ref, 'pre-release') && github.event.pull_request.merged == true
    steps:
      - name: Run shared release workflow
        id: call-workflow-release
        uses: project-llzk/open-source-release-helpers/.github/workflows/release.yml@main
        secrets: inherit
      - name: Run GitHub Pages deployment
        uses: ./.github/workflows/deploy-github-pages.yml
        secrets: inherit
        with:
          version: '${{ steps.call-workflow-release.outputs.version }}'
