//===-- CAPI.cpp ------------------------------------------------*- C++ -*-===//
//
// Part of the LLZK Project, under the Apache License v2.0.
// See LICENSE.txt for license information.
// Copyright 2025 Veridise Inc.
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
///
/// \file
/// This file includes the autogenerated CAPI functions to load the passes.
///
//===----------------------------------------------------------------------===//

#include <mlir/CAPI/Pass.h>

#include "pcl-conv/Transforms/TransformationPasses.capi.h.inc"
#include "pcl-conv/Transforms/TransformationPasses.h" // IWYU pragma: keep

using namespace pcl::conversion;

// Impl
#include "pcl-conv/Transforms/TransformationPasses.capi.cpp.inc"
